### ISSUE TITLE
How can I edit the script to change the /output variable?

### ISSUE THREAD

**Issue by LargeTalons** [jlesage/docker-filebot#10]
Hi,

So, the script is working great, but there is a problem when keeplink or symbolic link is being used as the method for file renaming.

The original filename is being linked to /output/TV/*show name*/*show file* instead of /mnt/user/TV/*show name*/*show file* 

To fix this, I need to be able to map /mnt/user (container) >> /mnt/user in the docker settings

How do I go about editing the script so that I can fix this? I dont see the script in the config file. Am I overlooking it? 

Thanks for including this in the docker, by the way!

**Comment by jlesage** [comment]
With the `keeplink` action, did you try to set the full path in the tv series format?  For example, you could set the `AMC_SERIES_FORMAT` to `/mnt/user/{plex}`.  Obviously, you need to make sure that `mnt/user` on the host is mapped to `/mnt/user` in the container.

> How do I go about editing the script so that I can fix this? I dont see the script in the config file. Am I overlooking it?

Are you talking about the AMC script?  This script is provided by Filebot and is not editable.  All the AMC script behaviour is configurable via environment variables.

**Comment by LargeTalons** [comment]
I figured it out :)

My problem is that filebot creates relative links when using keeplink and
my torrent client doesnt see the data with those.

I found out that this is by design and I'll have to figure how to convert
the links filebot creates. I thought it was something wrong I was doing
with the docker but it was not.

**Comment by jlesage** [comment]
If it can help, you now have the ability, with the latest image, to configure the input and output folders of the AMC script.
