### ISSUE TITLE
[Feature request] linux/arm/v8 docker image

### ISSUE THREAD

**Issue by glensc** [jlesage/docker-filebot#103]
### Idea

please build linux/arm/v8  docker image.

```
# docker pull jlesage/filebot
Using default tag: latest
latest: Pulling from jlesage/filebot
no matching manifest for linux/arm/v8 in the manifest list entries
```

also provide instructions to build on our own for unsupported platforms:

```
# docker build -t filebot . 
Sending build context to Docker daemon  1.735MB
Step 1/44 : ARG DOCKER_IMAGE_VERSION=
Step 2/44 : ARG FILEBOT_VERSION=5.1.2
Step 3/44 : ARG MEDIAINFOLIB_VERSION=23.10
Step 4/44 : ARG ZENLIB_VERSION=0.4.41
Step 5/44 : ARG UNRAR_VERSION=6.1.7
Step 6/44 : ARG FILEBOT_URL=https://get.filebot.net/filebot/FileBot_${FILEBOT_VERSION}/FileBot_${FILEBOT_VERSION}-portable.tar.xz
Step 7/44 : ARG MEDIAINFOLIB_URL=https://mediaarea.net/download/source/libmediainfo/${MEDIAINFOLIB_VERSION}/libmediainfo_${MEDIAINFOLIB_VERSION}.tar.xz
Step 8/44 : ARG ZENLIB_URL=https://mediaarea.net/download/source/libzen/${ZENLIB_VERSION}/libzen_${ZENLIB_VERSION}.tar.gz
Step 9/44 : ARG UNRAR_URL=https://www.rarlab.com/rar/unrarsrc-${UNRAR_VERSION}.tar.gz
Step 10/44 : FROM --platform=$BUILDPLATFORM tonistiigi/xx AS xx
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
```

**Comment by jlesage** [comment]
`linux/arm/v8` is not a valid combination.  Looks like you are you using a 32bits docker installation on a 64bits OS ?

**Comment by jlesage** [comment]
I should have realized this sooner, but the FileBot Docker image is not supported on ARM 32bits.  Only 64 bits.  See https://hub.docker.com/r/jlesage/filebot/tags.

So in your case, you should probably use/install the full 64bits version (kernel and user space) of RaspBerry PI OS instead.

By the way, if you execute `docker pull linuxserver/plex` to get the latest version, you should run into the same issue.

**Comment by glensc** [comment]
I'm thinking perhaps I can install 64bit docker (kernel already 64 bit), as I can't replace the os right now (no sd card writer)

```
root@chuxly /etc/apt# dpkg --print-foreign-architectures 
arm64
```

**Comment by jlesage** [comment]
Does `file /usr/bin/dpkg` indicate a 32 or 64bits binary ?

Yes, if you can install a 64bits version of Docker that would work.
