### ISSUE TITLE
Keeps crashing when trying to add items to filebot

### ISSUE THREAD

**Issue by pinkairfreshener** [jlesage/docker-filebot#108]
### Current Behavior

Loads fine. I go to add files and when I try to add stuff it crashes and restarts. However, I have realised that it lets me view folders but every mkv file within all of my sub-folders is greyed out for some reason. This never used to happen and it used to work very well. I have the correct user id and group id so I am not sure what I am doing wrong. I am using 84% of my storage so that also should not be an issue.

### Expected Behavior

Should allow me to add files for renaming/ hardlinking.

### Steps To Reproduce

Click "load" and try to add something.

### Environment

- OS: Debian
- OS version: Debian 6.1.76-1 (2024-02-01)
- CPU: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
- Docker version: Docker version 26.0.1, build d260a54
- Device model: Container runs on a linux server. I am trying to access on Macbook Pro (M1 Pro).
- Browser/OS: Firefox on mac.

### Container creation

services:
  filebot:
    image: jlesage/filebot:latest
    container_name: filebot
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=Europe/London
      - WEB_LISTENING_PORT=5300
    ports:
      - "5300:5300"
    volumes:
      - "/home/user/apps/filebot:/config:rw"
      - "/home/user:/data:rw"
    restart: unless-stopped

### Container log

```text
https://privatebin.net/?1df60079a939addf#HXpqDgZNKyvKV8QZKnyLEmrxidZTFrBvGXHNCvuHkKZE
```

**Comment by jlesage** [comment]
Few questions:
- When the crash occurs exactly ? Just by loading files, without renaming ?
- Do you have the same problem when loading one file ?
  - If yes, do you have the same problem with different files ?
- Can you try to add the following variable to see if it makes a difference: `FILEBOT_CUSTOM_OPTIONS=-no-xattr`
- Do you have the same problem with the previous version of the container image ?

**Comment by jlesage** [comment]
Closing this issue. Please re-open if needed.
