### ISSUE TITLE
Allow specifying custom input and output directories for AMC script

### ISSUE THREAD

**Issue by skylord123** [jlesage/docker-filebot#12]
Currently it doesn't look like you can override the input and output directories for the AMC script.

If the input and output directory are mounted separately in two different volumes then moving files becomes much slower. If both the input and output directory share a common parent directory it is better to mount that so that moving files is near instant.

The main reason I require this is because I have filebot move the files into my media folder but then symlink back to the download folder so I can continue seeding. If the volumes don't share the same structure as the host then symlinks created in the Filebot container wont work from the host.

Thanks :)

**Comment by jlesage** [comment]
This is now implemented with the latest image :smile:

**Comment by maxexcloo** [comment]
How would I use this? I'm having trouble with hardlinks in unRAID, my setup looks like this:

https://i.imgur.com/7aActW4.png

Appreciate the help and realize this may not be the ideal place to ask - hope it's okay!

**Comment by skylord123** [comment]
@maxexcloo it's pretty easy. I finally got time to setup this container and it went flawlessly.

You need to hit the "Show More Settings` drop down and then fill out "Automated Media Center: Input Directory" and "Automated Media Center: Output Directory". You basically set these to the exact paths you set up above for your input and output directories.

You will want to make sure you mount your directories usnig a common parent. Since my Input directory is `/mnt/user/appdata/media/filebot_paid_process` and my output is `/mnt/user/appdata/media/Videos` I mount `/mnt/user/appdata/media` as `/media` to the container since it is the parent folder both my input and output directory share. This way links generated between the two directories will work within the container and on the host since the path structure is the same.

Here is a picture of how I have it setup for example:
![screencapture-192-168-1-10-Docker-UpdateContainer-2020-01-05-05_24_47](https://user-images.githubusercontent.com/3412313/71780128-008e5700-2f7c-11ea-9496-8f018dabaf15.png)
I just removed the input and output directory paths and mounted it like I said (and since you specify it down below it doesn't matter).

**Comment by maxexcloo** [comment]
@skylord123 did you add the Media variable yourself? Mine doesn't have that (just confirming if there's any reason for it 😄)

Also, in your media formats (TV Shows, Movies, Music, etc) does the leading directory overwrite the AMC defaults (aka Movies, TV Shows, Anime?)

**Comment by skylord123** [comment]
> @skylord123 did you add the Media variable yourself? Mine doesn't have that (just confirming if there's any reason for it )

Yes, I added this myself. You want to mount the same parent directory of both your input and output folders. I removed the input and output directories and just have one instead.

> Also, in your media formats (TV Shows, Movies, Music, etc) does the leading directory overwrite the AMC defaults (aka Movies, TV Shows, Anime?)

No. That is just pre-pending a path to the plex default. I would change those back to just `{plex}` if you want the normal naming. All of my video files are kept in a `Videos` subfolder so I added `Videos/` in front of `{plex}` so that it would go into the correct folder. You can set `Automated Media Center: Action` to `test` so that it doesn't actually run on the files and it dumps out to the console with what paths are going to be used. I recommend doing this to make sure everything is setup correctly and using the right paths.
