### ISSUE TITLE
Version for raspberry pi ?

### ISSUE THREAD

**Issue by HydrelioxGitHub** [jlesage/docker-filebot#13]
Everything is in the issue title. Is it possible for you to publish an arm version ?
Thank you for your work.

**Comment by jlesage** [comment]
This will eventually come.  We first need a baseimage supporting ARM...

**Comment by HydrelioxGitHub** [comment]
I'm a noob on docker and I don't realize how much work has to be done to get a baseimage. If I can help in some way...

**Comment by HydrelioxGitHub** [comment]
Any update on this ?

**Comment by kavejo** [comment]
+1 for the ARM version

**Comment by jlesage** [comment]
It's slowly progressing... I don't have enough free time !

**Comment by HydrelioxGitHub** [comment]
It's ok thanks for your time and your work by the way. My question was just about if it still a work in progress or if it has been paused.

**Comment by arkique** [comment]
Appreciate your work and I'm also looking forward to docker image I can run on my Rpi4

**Comment by HydrelioxGitHub** [comment]
Any progress on this ?

**Comment by HydrelioxGitHub** [comment]
Maybe this could help ?
https://collabnix.com/building-arm-based-docker-images-on-docker-desktop-made-possible-using-buildx/

**Comment by jlesage** [comment]
I'm still working on baseimage... While it's easy to manually build the image for arm, it's another story to integrated this with a generic and automatic build system.

**Comment by HydrelioxGitHub** [comment]
Could I help in any way with this issue ?

**Comment by mozartcorleone** [comment]
Any update on ARM version?

**Comment by jlesage** [comment]
Yes, this is still planned.  Baseimage almost done!

**Comment by chenks** [comment]
fingers cross for an arm64/v8 release soon

**Comment by chenks** [comment]
> Yes, this is still planned. Baseimage almost done!

hi, are we likely to see this?

**Comment by jlesage** [comment]
The latest image is now multi-arch and supports ARM64 :)

**Comment by chenks** [comment]
> The latest image is now multi-arch and supports ARM64 :)

hi, does that mean i can't use v1.0.2 on an arm device as only the latest image supports it?

**Comment by jlesage** [comment]
Correct, version `1.0.2` is almost 5 years old.  Support for ARM has been added recently.

**Comment by chenks** [comment]
damn, no good to me then.
i use 1.0.2 specifically as any newer version require a license to use.

**Comment by jlesage** [comment]
You are right, but at least the license if very cheap (6$ US / year).  It's a great way to support the author of FileBot :)

**Comment by chenks** [comment]
the amount of times i use it even $6 doesn't make it worth while.
