### ISSUE TITLE
Feature/Documentation Request - Pass through arbitrary definitions

### ISSUE THREAD

**Issue by rawlk** [jlesage/docker-filebot#14]
Hey! Thanks for the great container. Just starting to play with it but its looking super promising for my needs.

I'm using the AMC script with the /watch directory. In the past I've used `--def pushover=<APIKEY>` to enable pushover notifications. I'm assuming I can do this with the `AMC_CUSTOM_OPTIONS` though I guess I'm doing it incorrectly. 

Currently I get the following when it starts:
 `[amc] Illegal Argument: java.nio.file.NoSuchFileException: /run/s6/services/amc/pushover=<APIKEY> (pushover=<APIKEY>)`

Using `  -e AMC_CUSTOM_OPTIONS="pushover=<APIKEY>" \ `

Potentially related request, I'm using this pointed at an NFS mount. Unfortunately, NFS doesn't support extended attributes so I need to ask filebot to [not use them](https://www.filebot.net/forums/viewtopic.php?t=324) to prevent more error messages. Not sure how to push such an argument through to filebot directly, can I use the same amc_custom_options as above or is that only for the AMC script?

Thanks!

**Comment by jlesage** [comment]
Does the pushover API key contains any special characters, space, etc?

As for the `no-xattr` option, if you also need it or the UI, try to add the following argument:
```
-e FILEBOT_OPTS=no-xattr
```
Adding the option to `AMC_CUSTOM_OPTIONS` will take care of the AMC script.

**Comment by rawlk** [comment]
Seems  `-e FILEBOT_OPTS=no-xattr` gives some errors:

```
[app] starting FileBot...
Error: Could not find or load main class no-xattr
Error: Could not find or load main class no-xattr
[app] starting FileBot...
```

The pushover API keys look like: `k83jmqj5nef8u7krb7ermz8tb71vzx`

**Comment by rawlk** [comment]
Heres another example of an AMC definition I'd like to pass through: https://www.filebot.net/forums/viewtopic.php?t=1299#p7879

`--def deleteAfterExtract=y` - Deletes the original RAR files after AMC works its magic. Super useful in a semi-automatic workflow when you let filebot/amc do the extraction

**Comment by rawlk** [comment]
[Looks like](https://github.com/jlesage/docker-filebot/blob/e9096f765908c22077e4ebf0c82a7dececeb0cfb/rootfs/etc/services.d/amc/run#L141) you can pass the whole `--def VARNAME=VALUE` directly. Haven't played with the `FILEBOT_OPTS=no-xattr` yet

**Comment by rawlk** [comment]
https://github.com/jlesage/docker-filebot/blob/80f22a05cc7badee4672518f0612da68b6b3bf87/rootfs/opt/filebot/filebot#L52

Does $FILEBOT_OPTS need to be rearranged to: 
`$JAVA_OPTS  $CONTAINER_OPTS -jar "$FILEBOT_HOME/jar/filebot.jar" $FILEBOT_OPTS "$@" `

To me this seems like it wouldn't pass the options to the executable, though I haven't played in java in a long time

**Comment by rawlk** [comment]
Re-arranging worked. Guess I'll figure out how to send a PR, if thats OK @jlesage

**Comment by jlesage** [comment]
Thanks for the analysis.  I added a new environment variable that can be used to correctly pass arguments to FileBot.

Note that I did a typo in my original comment: The option should be `-no-xattr`, not `no-xattr`.

**Comment by rawlk** [comment]
Awesome, Thanks! 
 - 80f181dd3f6126618b64ee7cd56fc165604a10c5
