### ISSUE TITLE
AMC not detecting custom watch and output folder

### ISSUE THREAD

**Issue by PTBKoo** [jlesage/docker-filebot#17]
I have a single folder called Data mapped to Data in the container
![Screen Shot 2020-01-03 at 12 06 14 AM](https://user-images.githubusercontent.com/29348754/71713074-f2460c80-2dbc-11ea-9eb9-83b040665588.png)

I changed the AMC output and input variables to 
![Screen Shot 2020-01-03 at 12 09 23 AM](https://user-images.githubusercontent.com/29348754/71713146-5799fd80-2dbd-11ea-9639-67ae6fcccc1e.png)

Tried couple of different variations but it seems AMC cant detect any folders that arent mounted to /watch and /output

**Comment by jlesage** [comment]
You used wrong variables.  You should use `AMC_INPUT_DIR` and `AMC_OUTPUT_DIR`.

**Comment by PTBKoo** [comment]
That did the trick, was using the default variables that came with the container.
