### ISSUE TITLE
How to setup recursion?

### ISSUE THREAD

**Issue by burkesquires** [jlesage/docker-filebot#18]
Hello,
For the life of me I cannot figure out how to set the -r or -R or --recursion flag to have filebot search for media in subfolders. Can it be done or am I missing something? Thank for all your efforts!

**Comment by jlesage** [comment]
For the UI or the AMC script?

For the UI, you can add the `FILEBOT_CUSTOM_OPTIONS` variable and set its value to `--recursion`. For AMC, use the `AMC_CUSTOM_OPTIONS` variable instead.

https://github.com/jlesage/docker-filebot#environment-variables

**Comment by burkesquires** [comment]
Thank you!
