### ISSUE TITLE
Revers proxy

### ISSUE THREAD

**Issue by Kubilai12** [jlesage/docker-filebot#19]
I am sorry but i don t understand Proxy section

I use this reverse proxy:  [https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues?utf8=%E2%9C%93&q=](url)

I use domain for all other container application, each Container have a private local ip but not 127.0.0.1 all is good exept for filebot

when i modify conf file if i restart container, it s lost data i add

Can you explain me how can i do for access GUI ?

**Comment by jlesage** [comment]
Can you provide an example of config you do for a working container?

Also, when you say that your config is lost after restarting the container, which configuration are you talking about ?

**Comment by Kubilai12** [comment]
i use this for launch filebot container :

docker run -d -e VIRTUAL_HOST=subdomain.domain.com \
              -e LETSENCRYPT_HOST=subdomain.domain.com \
              -e LETSENCRYPT_EMAIL=my mail \
              -e PUID=1000 \
              -e PGID=1000 \
              -p 8080:8080 \
              -v /home/SeedboxData:/storage \
              -v /home/SeedboxConf/filebot:/config \
              --network=webproxy \
              --name filebot \
              jlesage/filebot


in nginx/conf default file i have this : 

# subdomain.domain.com
upstream subdomain.domain.com {
				## Can be connected with "webproxy" network
		# filebot
			**server 172.18.0.9 down;**

**Comment by jlesage** [comment]
Sorry I'm not sur to I properly understand your setup and how you configured things.

But what is the issue at the end?  Do you get an HTTP error ?

**Comment by Kubilai12** [comment]
It's ok with Traefik proxy
