### ISSUE TITLE
Unable to add expression to AMC_SERIES_FORMAT

### ISSUE THREAD

**Issue by Feanux3** [jlesage/docker-filebot#20]
Sorry if this isn't the best place for this and also sorry for the long post, I'm super new to all of this.

When I try to change `AMC_SERIES_FORMAT` from `{plex}` to my custom formatting it fails and completely kills the docker container, forcing me to remake it.

The format I'm trying to use works in the interface (localhost:5800) when I add a new expression to a new preset but fails to work when I add it via docker.

Here's the format I'm trying to use: 

> /storage/Media/TV Shows/{n} ({y})/{episode.special ? 'Special' : 'Season '+s.pad(2)}/{n} - {episode.special ? 'S00E'+special.pad(2) : s00e00} - {t.replaceAll(/[!:`'",?.]+/).replacePart(', Part 1')}

It comes from [this AMC script](https://pastebin.com/tBkD4Ezz) I was using on a previous repo that is no longer being maintained - [https://github.com/coppit/docker-filebot](https://github.com/coppit/docker-filebot).

Here's what docker is spitting out when I try to commit the change: 

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; docker run -d --restart=always --privileged -v /etc/localtime:/etc/localtime:ro --net=bridge -p 0.0.0.0:5800:5800/tcp -h "HMS" -e XDG_CACHE_HOME="/config/xdg/cache" -e AMC_INPUT_STABLE_TIME="10" -e AMC_CONFLICT="auto" -e AMC_INPUT_FOLDER="/watch" -e APP_NAME="FileBot" -e AMC_INTERVAL="1800" -e AMC_MOVIE_FORMAT="{plex}" -e DISPLAY=":0" -e AMC_SERIES_FORMAT="/storage/Media/TV Shows/{n} ({y})/{episode.special ? 'Special' : 'Season '+s.pad(2)}/{n} - {episode.special ? 'S00E'+special.pad(2) : s00e00} - {t.replaceAll(/[!:'",?.]+/).replacePart(', Part 1')}" -e PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -e OPENSUBTITLES_USERNAME="" -e OPENSUBTITLES_PASSWORD="" -e AMC_ARTWORK="n" -e AMC_SUBTITLE_LANG="" -e USER_ID="1000" -e S6_BEHAVIOUR_IF_STAGE2_FAILS="3" -e XDG_CONFIG_HOME="/config/xdg/config" -e AMC_MATCH_MODE="opportunistic" -e LANG="en_US.UTF-8" -e XDG_DATA_HOME="/config/xdg/data" -e AMC_ANIME_FORMAT="{plex}" -e AMC_ACTION="copy" -e AMC_OUTPUT_FOLDER="/output" -e AMC_CUSTOM_OPTIONS="" -e AMC_PROCESS_MUSIC="y" -e DISPLAY_WIDTH="1280" -e APP_USER="app" -e GROUP_ID="1000" -e DISPLAY_HEIGHT="768" -e AMC_MUSIC_FORMAT="{plex}" -e S6_SERVICE_DEPS="1" -e XDG_RUNTIME_DIR="/tmp/run/user/app" -v "/sharedfolders/Downloads/watch":"/watch":rw -v "/sharedfolders/AppData/FilebotV2":"/config":rw -v "/sharedfolders/Media":"/output":rw -v "/sharedfolders":"/storage":rw --name="FilebotV2" "jlesage/filebot:latest" 2>&1' with exit code '2':

```
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; docker run -d --restart=always --privileged -v /etc/localtime:/etc/localtime:ro --net=bridge -p 0.0.0.0:5800:5800/tcp -h "HMS" -e XDG_CACHE_HOME="/config/xdg/cache" -e AMC_INPUT_STABLE_TIME="10" -e AMC_CONFLICT="auto" -e AMC_INPUT_FOLDER="/watch" -e APP_NAME="FileBot" -e AMC_INTERVAL="1800" -e AMC_MOVIE_FORMAT="{plex}" -e DISPLAY=":0" -e AMC_SERIES_FORMAT="/storage/Media/TV Shows/{n} ({y})/{episode.special ? 'Special' : 'Season '+s.pad(2)}/{n} - {episode.special ? 'S00E'+special.pad(2) : s00e00} - {t.replaceAll(/[!:'",?.]+/).replacePart(', Part 1')}" -e PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -e OPENSUBTITLES_USERNAME="" -e OPENSUBTITLES_PASSWORD="" -e AMC_ARTWORK="n" -e AMC_SUBTITLE_LANG="" -e USER_ID="1000" -e S6_BEHAVIOUR_IF_STAGE2_FAILS="3" -e XDG_CONFIG_HOME="/config/xdg/config" -e AMC_MATCH_MODE="opportunistic" -e LANG="en_US.UTF-8" -e XDG_DATA_HOME="/config/xdg/data" -e AMC_ANIME_FORMAT="{plex}" -e AMC_ACTION="copy" -e AMC_OUTPUT_FOLDER="/output" -e AMC_CUSTOM_OPTIONS="" -e AMC_PROCESS_MUSIC="y" -e DISPLAY_WIDTH="1280" -e APP_USER="app" -e GROUP_ID="1000" -e DISPLAY_HEIGHT="768" -e AMC_MUSIC_FORMAT="{plex}" -e S6_SERVICE_DEPS="1" -e XDG_RUNTIME_DIR="/tmp/run/user/app" -v "/sharedfolders/Downloads/watch":"/watch":rw -v "/sharedfolders/AppData/FilebotV2":"/config":rw -v "/sharedfolders/Media":"/output":rw -v "/sharedfolders":"/storage":rw --name="FilebotV2" "jlesage/filebot:latest" 2>&1' with exit code '2':  in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/docker.inc(597): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/docker.inc(704): OMVRpcServiceDocker->runContainer(Array, Array)
#2 [internal function]: OMVRpcServiceDocker->modifyContainer(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('modifyContainer', Array, Array)
#5 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Docker', 'modifyContainer', Array, Array, 1)
#6 {main}
```

If you need any more info please let me know and thank you for any help you can provide. If this isn't the right place to post it please let me know. Thank you!

**Comment by jlesage** [comment]
Since the format is passed as an environment variable, there are some escaping to be performed.

Try to use http://escapeshellarg.onlinephpfunctions.com and use the escaped string as the value of the environment variable.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
