### ISSUE TITLE
AMC script force Group

### ISSUE THREAD

**Issue by josopu** [jlesage/docker-filebot#21]
Is there a way to force group when using the jlesage/filebot AMC script? It tends to use AniDB when I want TheTVDB. "Group: [Anime:nine]"

If you pass in --def ut_label=TV then it'll force TV mode, but I don't know how to include this on with the script.

**Comment by jlesage** [comment]
Did you try to add the option to the `AMC_CUSTOM_OPTIONS` environment variable?

```
AMC_CUSTOM_OPTIONS=--def ut_label=TV
```

**Comment by josopu** [comment]
Obviously I didn't research, thanks for your help and sorry lost your time.

**Comment by jlesage** [comment]
No problem :)
