### ISSUE TITLE
Filebot dont work nonstop?

### ISSUE THREAD

**Issue by oNdsen** [jlesage/docker-filebot#22]
When I restart the Filebot container, all data in the /watch folder are being processed. If I load Files at a later time, Filebot doesn't do anything until I restart the container.
I have currently set the following parameters:
- KEEP_APP_RUNNING=1
- AMC_ACTION=move
- AMC_CONFLICT=auto
- AMC_MATCH_MODE=opportunistic
- AMC_MUSIC_FORMAT=/output/Music/{n} - {album+'/'}{pi.pad(2)+'. '} {t}
- AMC_MOVIE_FORMAT=/output/Movies{fn.contains('2160') ? '4k':''}/{n} ({y})
- AMC_SERIES_FORMAT=/output/Serien/{n}/{'Season '+s}/{n} {s00e00} {t}
- AMC_CUSTOM_OPTIONS=--lang de

Are there other parameters to consider?

**Comment by jlesage** [comment]
The AMC script runs every `AMC_INTERVAL`.  By default, it's 1800 seconds (30 min).

You can reduce the interval if you want the script to be invoked quicker.

**Comment by oNdsen** [comment]
Thanks for the Hint!
