### ISSUE TITLE
ClassNotFoundException: javafx.concurrent.Task on v1.9.0 build

### ISSUE THREAD

**Issue by repudi8or** [jlesage/docker-filebot#23]
Mar 19, 2020 3:11:10 AM net.filebot.ui.rename.RenameAction lambda$actionPerformed$1
SEVERE: MOVE: ClassNotFoundException: javafx.concurrent.Task
java.lang.NoClassDefFoundError: javafx/concurrent/Task
	at net.filebot.ui.rename.RenameAction.lambda$actionPerformed$1(Unknown Source)
	at net.filebot.util.ui.SwingUI.withWaitCursor(Unknown Source)
	at net.filebot.ui.rename.RenameAction.actionPerformed(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	... 3 more

i see javafx.concurrent in modules of zulu13.29.9-ca-jdk13.0.2-linux_musl_x64 but not in jre

**Comment by yan059** [comment]
same thing for me 
<img width="719" alt="Capture d’écran 2020-03-19 à 12 09 24" src="https://user-images.githubusercontent.com/37675697/77061419-7bdba280-69da-11ea-8620-5f04cf1d5d0e.png">

**Comment by Sidirius** [comment]
> same thing for me
> <img alt="Capture d’écran 2020-03-19 à 12 09 24" width="719" src="https://user-images.githubusercontent.com/37675697/77061419-7bdba280-69da-11ea-8620-5f04cf1d5d0e.png">

Me too

**Comment by jlesage** [comment]
Looking at this, thanks!

**Comment by yan059** [comment]
Thanks to you ;-)

Envoyé de mon iPhone

**Comment by jlesage** [comment]
To prevent people from upgrading to this version, I changed the 'latest' tag to point to the previous, working version.

**Comment by yan059** [comment]
Ok thanks for your support

**Comment by bodiroga** [comment]
Thanks for looking into this @jlesage :+1:

**Comment by tork24** [comment]
Same issue. Is it possible to also go to the 4.9.1 version?

Thanks

**Comment by bodiroga** [comment]
As far as I know, the [latest version](https://github.com/jlesage/docker-filebot/releases/tag/v1.9.1) fixes this problem, so this issue should be closed.

Many thanks for your work @jlesage! :wink:
