### ISSUE TITLE
Changing web and VNC port

### ISSUE THREAD

**Issue by seb29470** [jlesage/docker-filebot#24]
Hello,

first of all thank you for all the work that is done on DOCKER and on the images you provide which are great.

I have a problem when I deploy several of your images and want to access them (for example FILEZILLA, JDOWNLOADER and FILEBOT on the same server). Only the last application started appears in the foreground (on the HTTP or VNC interface) and prevents me from accessing the others.
Is it possible to define a different access port for each container?

Again thank you for everything and sorry for my bad English.

Have a good day

**Comment by jlesage** [comment]
Yes, by default the containers run in `bridge` network mode, which allow you to map ports of the container to any port on your host.  This is done via the `-p` argument of the `docker run` command (command used to create the container).

**Comment by seb29470** [comment]
Hello,
thanks for the advice, indeed everything works wonderfully with port forwarding.
Your work is incredible.
Have a good Easter weekend.
