### ISSUE TITLE
Extra options

### ISSUE THREAD

**Issue by Mezilar** [jlesage/docker-filebot#25]
Good day!
Please tell me how can I pass the '-- lang' parameter to the script to get the name of the renamed files not in English? I can not understand. 
Thanks!

**Comment by oNdsen** [comment]
Looking also for this Option. Is it possible to explain how to add Multiple Custom Options via AMC to Filebot?
I need to specify --db and --lang
I already tried FILEBOT_CUSTOM_OPTIONS and AMC_CUSTOM_OPTIONS:
`- FILEBOT_CUSTOM_OPTIONS='--lang de --db TheMovieDB'`
Output:
`Illegal Argument: java.nio.file.NoSuchFileException: /storage/'--lang ('--lang)                                                                                            
Illegal Argument: java.nio.file.NoSuchFileException: /storage/de (de)`

**Comment by jlesage** [comment]
@Mezilar, you need to set the environment variable `AMC_CUSTOM_OPTIONS` to something like `--lang de`.  This can be done by adding the `-e` parameter to the docker run command: `-e AMC_CUSTOM_OPTIONS="--lang de"`

@oNdsen, which error do you have when using `AMC_CUSTOM_OPTIONS` ?

**Comment by oNdsen** [comment]
Used `- AMC_CUSTOM_OPTIONS="--lang de --db TheMovieDB"` and getting the Same Error:
`[amc] Illegal Argument: java.nio.file.NoSuchFileException: /run/s6/services/amc/"--lang ("--lang)                                                                                                                                                                                 
[amc] Illegal Argument: java.nio.file.NoSuchFileException: /run/s6/services/amc/de (de)`
Also the following on each Job:
`[amc] Argument[1]: File does not exist: "--lang                                                                                                                                                                                                                                   
[amc] Argument[2]: File does not exist: de`

**Comment by jlesage** [comment]
Did you removed the options from `FILEBOT_CUSTOM_OPTIONS` ?

**Comment by oNdsen** [comment]
> Did you removed the options from `FILEBOT_CUSTOM_OPTIONS` ?
yes of course :) thats why [amc] appears in logs.

**Comment by jlesage** [comment]
It's working for me... Can you prove the output of `docker inspect <container name` ?

**Comment by oNdsen** [comment]
A little bit too much Informations, for a Composer created Container, isnt it?
Right now i have the Container configured exactly like this:
`version: '3.3'
services:
    filebot:
        container_name: filebot
        restart: on-failure
        ports:
            - '5800'
            - '5900'
        environment:
            - USER_ID=0
            - GROUP_ID=0
            - KEEP_APP_RUNNING=1
            - AMC_INTERVAL=900
            - AMC_ACTION=move
            - AMC_CONFLICT=auto
            - AMC_MATCH_MODE=opportunistic
            - AMC_MUSIC_FORMAT=/output/Music/{n} - {album+'/'}{pi.pad(2)+'. '} {t}
            - AMC_MOVIE_FORMAT=/output/Movies{fn.contains('2160') ? '4k':''}/{n} ({y})
            - AMC_SERIES_FORMAT=/output/Serien/{n} ({y})/{'Season '+s}/{n} ({y}) - {s00e00} - {t}
        volumes:
            - '/Container/filebot/config:/config'
            - '/Container/filebot/storage:/storage'
            - '/Container/jdownloader/output/extracted:/watch'
            - '/Public/Plex:/output'
        image: 'jlesage/filebot:latest'`
Do you have in your Test Environment added more than 1 additional Option?
I tried it with the following code after AMC_SERIES_FORMAT
`- FILEBOT_CUSTOM_OPTIONS='--lang de --db TheMovieDB'`

**Comment by jlesage** [comment]
`FILEBOT_CUSTOM_OPTIONS` is *not* for the AMC script.  You should try to add:

`AMC_CUSTOM_OPTIONS=--lang de --db TheMovieDB`

Also, the `docker inspect` command allows to exactly see the actual content of the variable.

**Comment by oNdsen** [comment]
sorry, i copied the wrong Line. I used AMC_CUSTOM_OPTIONS.
But maybe the Problem exists when i use „“? Need to try later.

**Comment by oNdsen** [comment]
Thats it! It only works without Quotes. Thanks a lot!
