### ISSUE TITLE
--def deleteAfterExtract=y option?

### ISSUE THREAD

**Issue by GitJamz** [jlesage/docker-filebot#26]
In my logs I see that it says it deleted the extracted files but it didnt.. So I think maybe this amc option is not invoked anywhere?
https://www.filebot.net/amc.html

container has permissions to delete because I manually started a shell in the container and went to the specific folder and deleted manually. no problems.."

**Comment by jlesage** [comment]
I would check the permissions and ownership of the files to be sure.

When you start a shell in the container, you are running as root, so you won't have any issue with permission.  FileBot/AMC however, is not running as root.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
