### ISSUE TITLE
licence import

### ISSUE THREAD

**Issue by chocorem** [jlesage/docker-filebot#28]
Hello,

I pasted the the license file in the config directory, where there the cache, log, tmp directories are.

when starting the docker, the license is not taken into consideration

`HW: Linux 1a8f23b1c163 4.19.107-Unraid #1 SMP Sun Mar 8 14:34:03 CDT 2020 x86_64 GNU/Linux
STORAGE: btrfs [/] @ 38 GB | fuse.shfs [/storage] @ 4.0 TB | fuse.shfs [/watch] @ 3.9 TB | fuse.shfs [/output] @ 3.9 TB | fuse.shfs [/config] @ 179 GB | btrfs [/etc/resolv.conf] @ 38 GB | btrfs [/etc/hostname] @ 38 GB | btrfs [/etc/hosts] @ 38 GB
DATA: /config
Package: DOCKER
License: UNREGISTERED`

the script is invoiced, and I get a license error

`[amc] License Error: UNREGISTERED

[amc] ________________________________________________
[amc] / Please purchase a FileBot License: https://www.filebot.net/purchase.html#docker /`

**Comment by chocorem** [comment]
I found the solution, had to rename the file that is has no special signs and no capitals

**Comment by jlesage** [comment]
Could you share the name of the filename that was not working ?  Maybe there is something that can be enhanced/fixed to avoid these problems.
