### ISSUE TITLE
Update to FileBot 4.9.1

### ISSUE THREAD

**Issue by d1vanloon** [jlesage/docker-filebot#29]
# Summary

Update the packaged version of FileBot to version 4.9.1.

# Notes

The new version of FileBot includes many user experience improvements.

**Comment by bodiroga** [comment]
Hi @d1vanloon!

The latest docker-filebot version (https://github.com/jlesage/docker-filebot/releases/tag/v1.9.1) is based on FileBot 4.9.1. Give it a try! :+1:

**Comment by d1vanloon** [comment]
Thanks!
