### ISSUE TITLE
Cross-device link

### ISSUE THREAD

**Issue by silentjay1980** [jlesage/docker-filebot#30]
Hi,

Im not able to use hardlink via the amc script because filebot is throwing the abve error. Both folders are not only in the same filesystem, they're both in the same folder. heres a snippet of the error:

[HARDLINK] Failure: java.nio.file.FileSystemException: /output/Movies/Bad Boys for Life (2020)/Bad Boys for Life (2020).mkv -> /watch/Bad.Boys.for.Life.2020.UHD.BluRay.2160p.DTS-X.7.1.HEVC.REMUX-FraMeSToR/Bad.Boys.for.Life.2020.UHD.BluRay.2160p.DTS-X.7.1.HEVC.REMUX-FraMeSToR.mkv: Cross-device link
[amc] Processed 0 files
[amc] FileSystemException: /output/Movies/Bad Boys for Life (2020)/Bad Boys for Life (2020).mkv -> /watch/Bad.Boys.for.Life.2020.UHD.BluRay.2160p.DTS-X.7.1.HEVC.REMUX-FraMeSToR/Bad.Boys.for.Life.2020.UHD.BluRay.2160p.DTS-X.7.1.HEVC.REMUX-FraMeSToR.mkv: Cross-device link
[amc] Finished without processing any files
[amc] Abort (×_×)

**Comment by jlesage** [comment]
Hardlinks are failing because `/watch` and `/output` are different mount points in the container.
You need to adjust your setup to make sure the source and destination are under the same mount point.  So the volume you are mapping to the container must be the parent of both your watch folder and the output folder.  You may need to use `AMC_INPUT_DIR` and `AMC_OUTPUT_DIR`.

**Comment by silentjay1980** [comment]
thanks for the prompt response. please bear with me. im not quite following and im very new at docker.

they are both mounted to /volume1/Downloads/. /output goes to subfolder /complete. the watch folder is /seeding. but both are in Downloads.
is there an overall mount point im missing?

**Comment by jlesage** [comment]
Are you talking about mount points on the host side or container side ?  According to the log message you provided, you are using `/watch` and `/output` in the container.

To clarify things, could you share the full container config:
```
docker inspect <name of the container>
```

**Comment by silentjay1980** [comment]
root@nas:/volume1/.@root # docker inspect filebot
[
    {
        "Id": "f5662f8ddb8442d12cbee88344cecb362d08413e52eee7fc03f551008197a1e3",
        "Created": "2020-05-20T13:24:42.740637285Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2856,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-05-20T13:24:44.066938169Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:3993d18be1b0cb789e51d88371a98c026f7191c83afecc5bf6817bb07aaf91a4",
        "ResolvConfPath": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/containers/f5662f8ddb8442d12cbee88344cecb362d08413e52eee7fc03f551008197a1e3/resolv.conf",
        "HostnamePath": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/containers/f5662f8ddb8442d12cbee88344cecb362d08413e52eee7fc03f551008197a1e3/hostname",
        "HostsPath": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/containers/f5662f8ddb8442d12cbee88344cecb362d08413e52eee7fc03f551008197a1e3/hosts",
        "LogPath": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/containers/f5662f8ddb8442d12cbee88344cecb362d08413e52eee7fc03f551008197a1e3/f5662f8ddb8442d12cbee88344cecb362d08413e52eee7fc03f551008197a1e3-json.log",
        "Name": "/filebot",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/volume1/Downloads/:/storage",
                "/volume1/Downloads/seeding:/watch",
                "/volume1/Docker/filebot:/config",
                "/volume1/Downloads/complete:/output"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5800"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [
                "AUDIT_WRITE",
                "CHOWN",
                "DAC_OVERRIDE",
                "FOWNER",
                "FSETID",
                "KILL",
                "MKNOD",
                "NET_BIND_SERVICE",
                "NET_RAW",
                "SETFCAP",
                "SETGID",
                "SETPCAP",
                "SETUID",
                "SYS_CHROOT"
            ],
            "CapDrop": [
                "AUDIT_CONTROL",
                "BLOCK_SUSPEND",
                "DAC_READ_SEARCH",
                "IPC_LOCK",
                "IPC_OWNER",
                "LEASE",
                "LINUX_IMMUTABLE",
                "MAC_ADMIN",
                "MAC_OVERRIDE",
                "NET_ADMIN",
                "NET_BROADCAST",
                "SYSLOG",
                "SYS_ADMIN",
                "SYS_BOOT",
                "SYS_MODULE",
                "SYS_NICE",
                "SYS_PACCT",
                "SYS_PTRACE",
                "SYS_RAWIO",
                "SYS_RESOURCE",
                "SYS_TIME",
                "SYS_TTY_CONFIG",
                "WAKE_ALARM"
            ],
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/a62860da2666ce3770712ad0a5c91dac54aa62c7656460e1fefbb560faf6b735-init/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/99c468eec2b28cc8c1bd58df94d87fe13f13f465e2c971e92a1173290cd94ae0/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/1f5c3a8685b2255df9db6d5ab7d2d0d6e712660ced7723c8635c181a3069111d/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/89fa5166810888b34b16ac6dd2d4f8b079899fc5e3d524311f27a3e848da0f83/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/3ecdaa8c6bf0a6fec5d9bcf5e069cd07b0762a185a2c62668948b10173547c0d/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/c188a05faf7f808693a17e307c6b271cd6c39affc9603e42b536c8ddcf59f910/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/2a624911b87e7c0e154b68824dde609cfde346957c2c796f00e9459cb4a1a596/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/068f89c8cd62b259791535b9e1d9ad4e36d20b6c7bb83de8b108f1542e0b76fa/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/7c424520c78e78a7dcd1e7985d6ae99587da416c9e30da7b3c8810cef0e631a5/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/f4b00373077c9ef7808825a3c2fed950cb47527d27044a71790ea9d4265a2479/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/46a99beff7b749dcfb18a3b7f042defbf02b1a5edf1efae2f5e2af177c6ac281/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/97fed0a0fea483053e40bb0fe81ea9593df193afd2de3dbae9894e9097943d0c/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/6ea23696599bb69db7fb716dc4ed08cbd1f84214fbde0b6e67fa9819f05a04e0/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/8b11dc35876832d70d65d07e8ba04661f0130eab30c91a480908400d19d683ab/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/d5a549cb2818f09c839eb8e8bd7d938586d41cf16724cd7d4d7ac9cd5fac8a87/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/a066195047104c2b11ae665ec9793fa265ebb54119148f295d3e37d61549c092/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/8248efc5de7bf4aac8472da1ec1ce4644022fac9231e86cc69b731e217834e70/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/485585ce6717381066ad7e29dabfe38bd5a730591b374018c566546d248c5346/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/fe0812352b68d6743eacc029b208aa6c0a8a4d297b4cc6b5b1237d18c25d272a/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/b29c1d6c2746c0eebd1d02f88c7c3de0555852063c6ae7783eaec37fbe050fb3/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/9a1d445a1af2a657aa3cef2398d5a53868da35ba2e14ae2bacc2c3f499fe3f83/diff:/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/df82cc8bdfe1e0433d33288170c114d0e6a6ad157d8b693b03e8e59be49c261d/diff",
                "MergedDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/a62860da2666ce3770712ad0a5c91dac54aa62c7656460e1fefbb560faf6b735/merged",
                "UpperDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/a62860da2666ce3770712ad0a5c91dac54aa62c7656460e1fefbb560faf6b735/diff",
                "WorkDir": "/volume1/.@plugins/AppCentral/docker-ce/docker_lib/overlay2/a62860da2666ce3770712ad0a5c91dac54aa62c7656460e1fefbb560faf6b735/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/volume1/Downloads",
                "Destination": "/storage",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/Downloads/seeding",
                "Destination": "/watch",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/Docker/filebot",
                "Destination": "/config",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/volume1/Downloads/complete",
                "Destination": "/output",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "dcd55bbc3fd2",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
                "S6_SERVICE_DEPS=1",
                "USER_ID=1000",
                "GROUP_ID=1000",
                "APP_NAME=FileBot",
                "APP_USER=app",
                "XDG_DATA_HOME=/config/xdg/data",
                "XDG_CONFIG_HOME=/config/xdg/config",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "DISPLAY=:0",
                "DISPLAY_WIDTH=1280",
                "DISPLAY_HEIGHT=768",
                "AMC_INTERVAL=1800",
                "AMC_INPUT_STABLE_TIME=10",
                "AMC_ACTION=test",
                "AMC_CONFLICT=auto",
                "AMC_MATCH_MODE=opportunistic",
                "AMC_ARTWORK=n",
                "AMC_MUSIC_FORMAT={plex}",
                "AMC_MOVIE_FORMAT={plex}",
                "AMC_SERIES_FORMAT={plex}",
                "AMC_ANIME_FORMAT={plex}",
                "AMC_PROCESS_MUSIC=y",
                "AMC_INPUT_FOLDER=/watch",
                "AMC_OUTPUT_FOLDER=/output",
                "OPENSUBTITLES_USERNAME=",
                "OPENSUBTITLES_PASSWORD=",
                "AMC_SUBTITLE_LANG=",
                "AMC_CUSTOM_OPTIONS="
            ],
            "Cmd": [
                "/init"
            ],
            "Image": "jlesage/filebot:latest",
            "Volumes": {
                "/config": {},
                "/output": {},
                "/storage": {},
                "/watch": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2020-04-26T00:12:46Z",
                "org.label-schema.description": "Docker container for FileBot",
                "org.label-schema.name": "filebot",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "4831593be95c0e72fb0441bfd101c08544020087",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-filebot.git",
                "org.label-schema.version": "1.9.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "8bc89f4e3154c2af23195f9524dd388b9d11b2dd4a50811d2558559489e830b4",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/8bc89f4e3154",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "c3beffdd33b59905853de1ea315f365ea062ea514b749f1ec1ec95ab8855959d",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.4",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:04",
            "Networks": {
                "bridge": {
                    "IPAMConfig": {},
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "36a7c25ccb482529f628ab9eae4512971769ede965e29c5433b4d47d0eb02f42",
                    "EndpointID": "c3beffdd33b59905853de1ea315f365ea062ea514b749f1ec1ec95ab8855959d",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:04",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by jlesage** [comment]
Here you see that you mapped `/volume1/Downloads/seeding` to `/watch` and `/volume1/Downloads/complete` to `/output`"

```
{
"Type": "bind",
"Source": "/volume1/Downloads/seeding",
"Destination": "/watch",
"Mode": "",
"RW": true,
"Propagation": "rprivate"
},
{
"Type": "bind",
"Source": "/volume1/Downloads/complete",
"Destination": "/output",
"Mode": "",
"RW": true,
"Propagation": "rprivate"
}
```

So inside the container, you are using different mountpoints.  What you need to do is use a single mapping for both.  For example, you could map `/volume1/Downloads` to `/workdir`.

Then set `AMC_INPUT_FOLDER` to `/workdir/seeding` and `AMC_OUTPUT_FOLDER` to `/workdir/complete`.

**Comment by silentjay1980** [comment]
So just bind one working directory then use the env variables to set watch and output?

**Comment by Yop59** [comment]
Hi,

Sorry but I don't understand how to configure everything :(

For example, I have 2 folders:
- /mnt/look (for input)
- /mnt/move (for output)

On the host/volume side, I put :
- /watch -> /mnt/look
- /output -> /mnt/move

And on the container side ? I put :
- AMC_INPUT_FOLDER -> /mnt/look
- AMC_OUTPUT_FOLDER -> /mnt/move

Or on the host/volume side, I have to create a "map additional volume" :
- /workdir -> /mnt

And on the container side :
- AMC_INPUT_FOLDER -> /workdir/look
- AMC_OUTPUT_FOLDER -> /workdir/move

I'm completely lost....

Thanks a lot for your help.

**Comment by jlesage** [comment]
Yes, in your case one binding is need.  Choose the folder on the host that contains both your input and output files (e.g. `/volume1/Downloads`) and bind it to the container (at `/workdir` for example).   Then use variables to set the watch and output folders, from the container's point-of-view (e.g. `AMC_INPUT_FOLDER` = `/workdir/seeding` and `AMC_OUTPUT_FOLDER` = `/workdir/complete`).

Note that a binding for `/config` is always required.

**Comment by silentjay1980** [comment]
so for example as shown. /storage mapped to /volume1 downloads and the /config mapped wherever. delete the other two and change amc input to /storage/seeding and amc output to /storage/complete?

**Comment by jlesage** [comment]
Yes, this also works.

**Comment by revelous** [comment]
This may not be directly related, so please tell me if a new issue is warranted. In short, action clone doesn't seem to work properly on btrfs. My compose file is such:

```
  filebot:
    image: jlesage/filebot:latest
    container_name: filebot
    volumes:
      - ${DATADIR}/filebot:/config
      - ${MEDIADIR}:/media/output
      - ${DOWNLOADDIR}:/media/watch
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}
      - AMC_ACTION=clone
      - AMC_INPUT_DIR=/media/watch
      - AMC_OUTPUT_DIR=/media/output
      - AMC_INTERVAL=180
      - AMC_MOVIE_FORMAT=${FB_MOVIEFORMAT}
      - AMC_SERIES_FORMAT=${FB_SERIESFORMAT}
      - AMC_ANIME_FORMAT=${FB_SERIESFORMAT}
      - AMC_MUSIC_FORMAT=${FB_MUSICFORMAT}
    restart: unless-stopped
```
I would expect this to use cp --reflink=auto, but it's not. It's just a cp. 

This script run on the same host does use cp --reflink=auto:
`
filebot -script fn:amc -r "${DOWNLOADDIR}" -no-xattr --output "${MEDIADIR}" --action clone --conflict auto -non-strict --log-file=/var/log/amc.log "music=y" "seriesFormat=${FB_SERIESFORMAT}" "movieFormat=${FB_MOVIEFORMAT}" "musicFormat=${FB_MUSICFORMAT}" "excludeList=${excludeList}"`

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
