### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by 65308920** [jlesage/docker-filebot#31]
Hi,

The docker version filebot cannot support Chinese properly. Is it possible to develop the multilanguage function in this project?

**Comment by jlesage** [comment]
What is the issue exactly ?  Text is not displaying correctly ?

You can try to set the variable `ENABLE_CJK_FONT` to `1`.
https://github.com/jlesage/docker-filebot#environment-variables

**Comment by jlesage** [comment]
Closing issue.  Please re-open if needed.
