### ISSUE TITLE
"history.xml" file is not updated

### ISSUE THREAD

**Issue by bodiroga** [jlesage/docker-filebot#32]
Hi @jlesage!

As stated many times (but not enough), thanks for your work packing Filebot in this great docker image :wink: 

Anyway, I have seen a strange behaviour in the container that I want to report, but I'm not sure if it is just me or anyone else can confirm it. After renaming some files, the "history.xml" file in the 'config' folder is not updated until the container is restarted. Is this expected?

Best regards!

**Comment by jlesage** [comment]
This is probably a behaviour of Filebot itself, where it writes the file when it exits...

**Comment by bodiroga** [comment]
Yeah, that makes sense, thanks @jlesage! I will ask it to @rednoah on his forum, perhaps it is a feature request for Filebot, although it seems strange that the history file is not updated until the program is closed. Let's see what he says!

Awesome work, as always!

**Comment by rednoah** [comment]
`FileBot r8222` and above will now flush the history to file after you click `Rename` in the GUI. The CLI will continue to flush the history on exit (since the `amc script` needs to differentiate between `current-session-history` and `in-the-past-history` for various post-processing tasks).

**Comment by bodiroga** [comment]
Thank you @rednoah, wow, that was really fast!

Looking forward for the next release to try it out! :+1:

**Comment by bodiroga** [comment]
This works great on 1.11.1, thanks @jlesage!
