### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by magefesa** [jlesage/docker-filebot#34]
Great work ! 
1 questions:

1- If I want to specify an output Folder, what is the **user** to add R/W permissions ? If I turn **All users** works, but. is not the best option...

Thank you

**Comment by jlesage** [comment]
The `USER_ID` and `GROUP_ID` environment variables specify the user under which the container is running.  This same user should be allowed to write the the output folder.  Thus, the output folder should be owned by the same user, or it should have compatible permissions.

**Comment by magefesa** [comment]
PErfect now.. I ve created an specific permission for that user, although he belong to a group and that group had permissions... All solved thanks ! 
One more thing... Could be possible to include an environtment to send and email when AMC works ?
Is it possible to throw AMC on manual way throught terminal command ?

Thanks again

**Comment by jlesage** [comment]
Sorry for the delay on this...  Filebot/AMC has support for some notification mechanisms (including email).  Maybe you could use them.  See https://www.filebot.net/forums/viewtopic.php?f=4&t=215

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
