### ISSUE TITLE
AMC: Multiple instances?

### ISSUE THREAD

**Issue by WirlyWirly** [jlesage/docker-filebot#35]
Just wondering if there's a way to run multiple AMC scripts in a single container. At the moment I'm using a single parent folder, with child folders for "TV" and another for "Movies". I'd like to force the `ut_label=TV` option and `ut_label=Movie` for each respective folder, especially since I also throw anime into the "TV" folder and like using TVDB instead of AniDB.

I know I could just make another container pointing to each folder, but I thought I'd try to save some resources and see if I can run two instances of AMC with their own settings.

Also, is there an "exclude_folder" option that I'm missing? I have a 3rd child-folder that I'd like it to ignore, but again I don't see an option for it.

P.S
It'd be great if there was a env variable we could specify to disable everything except AMC. I know that you can just exclude port exposure, but having a web-service running in the background indefinitely seems like a waste.

**Comment by jlesage** [comment]
> Just wondering if there's a way to run multiple AMC scripts in a single container. At the moment I'm using a single parent folder, with child folders for "TV" and another for "Movies". I'd like to force the `ut_label=TV` option and `ut_label=Movie` for each respective folder, especially since I also throw anime into the "TV" folder and like using TVDB instead of AniDB.
> 
> I know I could just make another container pointing to each folder, but I thought I'd try to save some resources and see if I can run two instances of AMC with their own settings.

Did you check on the Filebot forum to see if this can be already accomplished with AMC ?

> Also, is there an "exclude_folder" option that I'm missing? I have a 3rd child-folder that I'd like it to ignore, but again I don't see an option for it.

It seems that there is an option to ignore directories:
https://www.filebot.net/forums/viewtopic.php?t=5022
You can use the `AMC_CUSTOM_OPTIONS` environment variable to set this option.

> P.S
> It'd be great if there was a env variable we could specify to disable everything except AMC. I know that you can just exclude port exposure, but having a web-service running in the background indefinitely seems like a waste.

Yes, this is eventually be possible :)

**Comment by WirlyWirly** [comment]
Thanks for the help! I was only reading through the documentation, I didn't browse much around the forums. I'll mark this as closed since it seems that my answers were already answered there.
