### ISSUE TITLE
Dark mode/theme functionality?

### ISSUE THREAD

**Issue by evil-p-anda** [jlesage/docker-filebot#36]
Is there anyway of incorporating different themes? Eg [Choose Java Swing Look-and-Feel (e.g. Dark Mode)](https://www.filebot.net/forums/viewtopic.php?t=9827)

Would be great if this functionality was able to be added for Docker usage somehow.

**Comment by jlesage** [comment]
Executing the commands from the link you provided seems to work.  For example:
```
docker exec <container name> /opt/filebot/filebot -script fn:properties --def net.filebot.theme=Darcula
```
Then restart the container.

**Comment by PriamX** [comment]
That works great for the filebot app window. Is there an equally easy fix for the white space around the app window?
![filebot-darkula](https://user-images.githubusercontent.com/43935458/95057367-4f0b8600-06b3-11eb-8ec0-b896a325c7ee.JPG)

**Comment by jlesage** [comment]
Unfortunately there is no easy fix for this yet...

**Comment by PriamX** [comment]
Understood. Thanks for replying.

**Comment by jlesage** [comment]
Dark mode is not properly supported with latest version of the image.

**Comment by jlesage** [comment]
Fixed previous comment: dark mode is **now** properly supported...
