### ISSUE TITLE
AMC_OUTPUT_DIR and AMC_OUTPUT_FOLDER

### ISSUE THREAD

**Issue by nolazybits** [jlesage/docker-filebot#37]
~it seems both exist and both need to be defined to the same value.~
Is this a refactoring leftover?

those are left overs in your dockerfile, meaning in portainer or other docker gui the env get populated, although not used anymore

**Comment by jlesage** [comment]
Yes you are right... Wrong variable names in the Dockerfile.  I will fix this, thanks!

**Comment by jlesage** [comment]
This is fixed with the latest image.
