### ISSUE TITLE
[amc] LicenseError: Unauthorized

### ISSUE THREAD

**Issue by Guruleenyc** [jlesage/docker-filebot#38]
I have the license file (.psm) in the /config path of the unraid filebot docker, but it is still not recognizing it. I get this in the logs:
[amc] LicenseError: Unauthorized

**Comment by jlesage** [comment]
Was the license working before or you just installed it ?

**Comment by Guruleenyc** [comment]
Yes.

**Comment by jlesage** [comment]
Can you provide the output of the following command:
```
docker exec FileBot /opt/filebot/filebot -script fn:sysinfo
```

**Comment by jlesage** [comment]
Closing issue, please reopen if needed.
