### ISSUE TITLE
How to run from command-line?

### ISSUE THREAD

**Issue by monalisa-overdrive** [jlesage/docker-filebot#39]
How can I run filebot CLI?

I have it configured to run an AMC script and can access the webUI fine, but there's some testing I want to do with the AMC script and I don't want to have to update/restart the container every time to reload the script configs.

I tried `docker exec -it filebot sh` but when I try to run filebot commands, I get `sh: filebot: not found`

**Comment by checktravis** [comment]
I am looking for this as well.

This works:
```
docker exec filebot /opt/filebot/filebot -version
FileBot 4.9.1 (r7372) JDK8 / OpenJDK Runtime Environment 1.8.0_242 / Linux 5.4.0-48-generic (amd64)
```

But this just hangs
```
docker exec filebot /opt/filebot/filebot -rename "/storage/What It's Like Being Alone"
```

**Comment by jlesage** [comment]
`docker exec filebot /opt/filebot/filebot` is the way to manually invoke the FileBot CLI.

**Comment by jlesage** [comment]
@checktravis, it can take some time to execute, did you wait enough long?  Maybe add `--log all` to see any activity ?

**Comment by checktravis** [comment]
I'll try that

**Comment by Speedmod88** [comment]
Hi, I have this issues too...

using your Unraid Docker:

open the Console:

> /tmp # docker exec filebot /opt/filebot/filebot
> sh: docker: not found

I got this in the console

do I have to do something else to activate the docker cmd?

or is AMC already use the duplicate script?  -> filebot -script dev:duplicates /path

to scan all duplicates from metadata and not from path?

Thanks You
Best Regards

**Comment by jlesage** [comment]
You seem to have executed the command from inside the container.  The command must be run on the host (unRAID) instead.

Also, in your case, the command should be:
```
docker exec FileBot /opt/filebot/filebot
```
(you must use the correct container name)

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
