### ISSUE TITLE
s6-envdir: fatal: unable to envdir: Permission denied

### ISSUE THREAD

**Issue by ahowell82** [jlesage/docker-filebot#4]
Have openmediavault with this docker; keep receiving the error `s6-envdir: fatal: unable to envdir: Permission denied` on a never ending loop.

Configuration:
`[
    {
        "Id": "7be3537baa873035c5125e5ffca5d779199e8b8d2e0787c40dfcd414fec04a8a",
        "Created": "2019-03-17T17:41:05.723290215Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 17162,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-03-17T17:41:07.721764789Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:fdbde96f2f3461014ce9c7a6344275b93950eb2e9a5338151c55244e24961c96",
        "ResolvConfPath": "/srv/dev-disk-by-label-raid3TBa/docker/containers/7be3537baa873035c5125e5ffca5d779199e8b8d2e0787c40dfcd414fec04a8a/resolv.conf",
        "HostnamePath": "/srv/dev-disk-by-label-raid3TBa/docker/containers/7be3537baa873035c5125e5ffca5d779199e8b8d2e0787c40dfcd414fec04a8a/hostname",
        "HostsPath": "/srv/dev-disk-by-label-raid3TBa/docker/containers/7be3537baa873035c5125e5ffca5d779199e8b8d2e0787c40dfcd414fec04a8a/hosts",
        "LogPath": "/srv/dev-disk-by-label-raid3TBa/docker/containers/7be3537baa873035c5125e5ffca5d779199e8b8d2e0787c40dfcd414fec04a8a/7be3537baa873035c5125e5ffca5d779199e8b8d2e0787c40dfcd414fec04a8a-json.log",
        "Name": "/filebot",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro",
                "/sharedfolders/appdata/filebot/storage:/storage:rw",
                "/sharedfolders/appdata/filebot/config:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/srv/dev-disk-by-label-raid3TBa/docker/overlay2/c169a93a018441fdffa12bfcb46a71ad84bb10f26dce26808a3410bce0a9d3ea-init/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/ce5be2f2bca8396e6816780adf0a3c7c2f8099d18924b8d80a3aa8a6a5f4b6c9/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/9f7b8e69c8c1df515dcb36c782308faed78487ce4948b82857f5f2f1098d362c/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/784811e3e67f85ff5b3029a1c9e2b1b3e493ea2ccacf17e14e666104623e8b08/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/a4fa048c605705386529dc960ffe08c1cbf01c1483ee29a14e682c83a03d1e60/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/21775b735c4cabf00eec6ed97fbb54cad98d5280dca2bde2ba8d41b554f768ab/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/dc664e682311fa0894301b3dbe5bd77fee8fb14b9349ba4b3a8f2ae9f467231e/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/5246e81d423788143b2cffc00de6249c11aa63ea160720009a64346dd5473c99/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/ba3be42d7394992cbda2ba34fef434aae300ea9f543b81d85f05129eae085e92/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/76f98361cd5456b9148a1cfa1aedaf3b1112c3a943f89f387c28f551a48021eb/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/c457f883c8f566cd5eb126c7a12e20841774e53c6d5ab89bd5be6b6a69c143b7/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/9794a2a2f65e58f0a1b600316c512be809fc29be4792114be79bcd229260bedc/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/d51ddd1491a0eb520f48b0f92c2f3eb9dd33531faeac8cef8dcec174b88cc750/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/ece3be70f7acd19d6190d4b891c37b604107e448813617e6f0287a013924d6d7/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/02a62d89826f0a8afe22fa5103a7708f77bd6a8544a5ce0167c64096994bb8b4/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/7651c4dc6ce7378f12bb6140074a7103d90726399e71ec88ed77a0ce7171b15e/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/92854a2740fb1419b719025436811f6d806b73021e4c17b70fee034ab6f0fd03/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/8969a3214e4c6780906fe0ea46c817a4bd6ac0b5242f3be5ce4c9626cc9bfbd7/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/ad5cf8bc838475e831971f75bebddb55678e8740c3495361132307f5d65e3d8a/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/821d8f223fcd971fada3f76a4028129e74706782d496a3557bf8962adacaef8e/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/587c880e3f739a32b7f9d6bf4e4fcabd9f02d50e3016de165ffab68e48268c10/diff:/srv/dev-disk-by-label-raid3TBa/docker/overlay2/06bbda0b2a5e7e64fc327028760cda446f4c83d1b60d84cbde78c1084e5e22fb/diff",
                "MergedDir": "/srv/dev-disk-by-label-raid3TBa/docker/overlay2/c169a93a018441fdffa12bfcb46a71ad84bb10f26dce26808a3410bce0a9d3ea/merged",
                "UpperDir": "/srv/dev-disk-by-label-raid3TBa/docker/overlay2/c169a93a018441fdffa12bfcb46a71ad84bb10f26dce26808a3410bce0a9d3ea/diff",
                "WorkDir": "/srv/dev-disk-by-label-raid3TBa/docker/overlay2/c169a93a018441fdffa12bfcb46a71ad84bb10f26dce26808a3410bce0a9d3ea/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/sharedfolders/appdata/filebot/storage",
                "Destination": "/storage",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/sharedfolders/appdata/filebot/config",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "ba46464d8bf0",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "XDG_CONFIG_HOME=/config/xdg/config",
                "DISPLAY_HEIGHT=768",
                "USER_ID=1001",
                "S6_SERVICE_DEPS=1",
                "XDG_CACHE_HOME=/config/xdg/cache",
                "APP_NAME=FileBot",
                "XDG_RUNTIME_DIR=/tmp/run/user/app",
                "APP_USER=app",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "KEEP_APP_RUNNING=1",
                "DISPLAY_WIDTH=1280",
                "GROUP_ID=100",
                "XDG_DATA_HOME=/config/xdg/data",
                "DISPLAY=:0",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=3"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "jlesage/filebot:latest",
            "Volumes": {
                "/config": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.label-schema.description": "Docker container for FileBot",
                "org.label-schema.name": "filebot",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-filebot",
                "org.label-schema.version": "1.2.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "7e237e70e84e68cef1bbd66e41099c923439415348bbec92c73f7a6b579f23df",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": null,
                "5900/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/7e237e70e84e",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "b9509281cb441b0e19f347e4b07cadd40de256c1000b79863a95dac22234cc2d",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.3",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:03",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "1a993567f768e80d7b422b5668595b0e2f08687b5b64be23effe39fb3eaecb09",
                    "EndpointID": "b9509281cb441b0e19f347e4b07cadd40de256c1000b79863a95dac22234cc2d",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:03",
                    "DriverOpts": null
                }
            }
        }
    }
]`

**Comment by jlesage** [comment]
Could you also provide the container's log?

**Comment by ahowell82** [comment]
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] filebot.sh: executing...
[cont-init.d] filebot.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting certsmonitor...
[services.d] starting nginx...
[services.d] starting xvfb...
[nginx] starting...
[certsmonitor] disabling service: secure connection not enabled.
[xvfb] starting...
[services.d] starting x11vnc...
[services.d] starting statusmonitor...
[x11vnc] starting...
22/03/2019 11:38:49 passing arg to libvncserver: -rfbport
22/03/2019 11:38:49 passing arg to libvncserver: 5900
22/03/2019 11:38:49 passing arg to libvncserver: -rfbportv6
22/03/2019 11:38:49 passing arg to libvncserver: -1
22/03/2019 11:38:49 passing arg to libvncserver: -httpportv6
22/03/2019 11:38:49 passing arg to libvncserver: -1
22/03/2019 11:38:49 passing arg to libvncserver: -desktop
22/03/2019 11:38:49 passing arg to libvncserver: FileBot
22/03/2019 11:38:49 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 776
[statusmonitor] no file to monitor: disabling service...
[services.d] starting logmonitor...
[services.d] starting openbox...
[logmonitor] no file to monitor: disabling service...
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
22/03/2019 11:38:49 Using X display :0
22/03/2019 11:38:49 rootwin: 0x43 reswin: 0x200001 dpy: 0xbbab19e0
22/03/2019 11:38:49
22/03/2019 11:38:49 ------------------ USEFUL INFORMATION ------------------
22/03/2019 11:38:49 X DAMAGE available on display, using it for polling hints.
22/03/2019 11:38:49   To disable this behavior use: '-noxdamage'
22/03/2019 11:38:49
22/03/2019 11:38:49   Most compositing window managers like 'compiz' or 'beryl'
22/03/2019 11:38:49   cause X DAMAGE to fail, and so you may not see any screen
22/03/2019 11:38:49   updates via VNC.  Either disable 'compiz' (recommended) or
22/03/2019 11:38:49   supply the x11vnc '-noxdamage' command line option.
22/03/2019 11:38:49 X COMPOSITE available on display, using it for window polling.
22/03/2019 11:38:49   To disable this behavior use: '-noxcomposite'
22/03/2019 11:38:49
22/03/2019 11:38:49 Wireframing: -wireframe mode is in effect for window moves.
22/03/2019 11:38:49   If this yields undesired behavior (poor response, painting
22/03/2019 11:38:49   errors, etc) it may be disabled:
22/03/2019 11:38:49    - use '-nowf' to disable wireframing completely.
22/03/2019 11:38:49    - use '-nowcr' to disable the Copy Rectangle after the
22/03/2019 11:38:49      moved window is released in the new position.
22/03/2019 11:38:49   Also see the -help entry for tuning parameters.
22/03/2019 11:38:49   You can press 3 Alt_L's (Left "Alt" key) in a row to
22/03/2019 11:38:49   repaint the screen, also see the -fixscreen option for
22/03/2019 11:38:49   periodic repaints.
22/03/2019 11:38:49 GrabServer control via XTEST.
22/03/2019 11:38:49
22/03/2019 11:38:49 Scroll Detection: -scrollcopyrect mode is in effect to
22/03/2019 11:38:49   use RECORD extension to try to detect scrolling windows
22/03/2019 11:38:49   (induced by either user keystroke or mouse input).
22/03/2019 11:38:49   If this yields undesired behavior (poor response, painting
22/03/2019 11:38:49   errors, etc) it may be disabled via: '-noscr'
22/03/2019 11:38:49   Also see the -help entry for tuning parameters.
22/03/2019 11:38:49   You can press 3 Alt_L's (Left "Alt" key) in a row to
22/03/2019 11:38:49   repaint the screen, also see the -fixscreen option for
22/03/2019 11:38:49   periodic repaints.
22/03/2019 11:38:49
22/03/2019 11:38:49 XKEYBOARD: number of keysyms per keycode 7 is greater
22/03/2019 11:38:49   than 4 and 51 keysyms are mapped above 4.
22/03/2019 11:38:49   Automatically switching to -xkb mode.
22/03/2019 11:38:49   If this makes the key mapping worse you can
22/03/2019 11:38:49   disable it with the "-noxkb" option.
22/03/2019 11:38:49   Also, remember "-remap DEAD" for accenting characters.
22/03/2019 11:38:49
22/03/2019 11:38:49 X FBPM extension not supported.
Xlib:  extension "DPMS" missing on display ":0".
22/03/2019 11:38:49 X display is not capable of DPMS.
22/03/2019 11:38:49 --------------------------------------------------------
22/03/2019 11:38:49
22/03/2019 11:38:49 Default visual ID: 0x21
22/03/2019 11:38:49 Read initial data from X display into framebuffer.
22/03/2019 11:38:49 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
22/03/2019 11:38:49
22/03/2019 11:38:49 X display :0 is 32bpp depth=24 true color
22/03/2019 11:38:49
22/03/2019 11:38:49 Listening for VNC connections on TCP port 5900
22/03/2019 11:38:49
22/03/2019 11:38:49 Xinerama is present and active (e.g. multi-head).
22/03/2019 11:38:49 Xinerama: number of sub-screens: 1
22/03/2019 11:38:49 Xinerama: no blackouts needed (only one sub-screen)
22/03/2019 11:38:49
22/03/2019 11:38:49 fb read rate: 1092 MB/sec
22/03/2019 11:38:49 fast read: reset -wait  ms to: 10
22/03/2019 11:38:49 fast read: reset -defer ms to: 10
22/03/2019 11:38:49 The X server says there are 10 mouse buttons.
22/03/2019 11:38:49 screen setup finished.
22/03/2019 11:38:49

The VNC desktop is:      ba46464d8bf0:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
s6-svwait: fatal: timed out
[services.d] starting app...
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[services.d] done.
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
[openbox] starting...
[app] starting FileBot...
s6-envdir: fatal: unable to envdir: Permission denied
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)
[openbox] starting...
How are you gentlemen? All your base are belong to us. (Openbox received signal 11)`

**Comment by jlesage** [comment]
I just tried on openmediavault running on a VM and the container is working file.
Do you have any special in container's settings?
Did you tried to pull the image again and re-create the container?

**Comment by ahowell82** [comment]
Could it be that I have the docker root location on a drive that is not the primary drive? 
Here is the fstab 
'/dev/disk/by-label/raid3TBa /srv/dev-disk-by-label-raid3TBa ext4 defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2'

**Comment by ahowell82** [comment]
Apologies, I completely missed the question of re-pulling the image & re-creating the container ... yes I have re-pulled the image & re-created the container many times

**Comment by ahowell82** [comment]
I went back in & set the off nominal docker root drive mount options to what the sda drive settings are & no change ... same error code. 

Next I'll try syncing the off nominal docker root data back to the nominal docker root & see what comes

**Comment by ahowell82** [comment]
Reverted to the default docker location & everything is working as desired. Looks like it has to do with the mountings. 

Thank you very much for all your help

**Comment by jlesage** [comment]
Great to see that it's now working for you.
