### ISSUE TITLE
batch script after automatic renaming

### ISSUE THREAD

**Issue by tony77682** [jlesage/docker-filebot#40]
Hello,
how to call a batch script after automatic renaming.  I tried the "AMC_CUSTOM_OPTIONS" argument, but it didn't work.
thank you

**Comment by jlesage** [comment]
`--def exec` seems to be the option to use:
https://www.filebot.net/forums/viewtopic.php?t=3880

You can set the option in `AMC_CUSTOM_OPTIONS`.

**Comment by tony77682** [comment]
To be precise run a curl command with my script, but I don't know how to run the script.

**Comment by jlesage** [comment]
If you copy your bash script to the folder you mapped to `/config`, the `AMC_CUSTOM_OPTIONS` variable would contain something like:
```
--def exec /config/myscript.sh
```

**Comment by tony77682** [comment]
thanks for your advices
 but i can't run curl command because curl package is not included in your image:

 [amc] Execute: /config/scan.sh
 [amc] /config/scan.sh: line 3: curl: command not found
 [amc] /config/scan.sh: line 4: curl: command not found

 is it possible to add the curl package in your image?

**Comment by jlesage** [comment]
You can install custom packages using the `AMC_INSTALL_PKGS` environment variable.  See https://github.com/jlesage/docker-filebot#environment-variables.

**Comment by tony77682** [comment]
I'm sorry, I hadn't seen this possibility!
Thank you for taking the time to help me!

**Comment by jlesage** [comment]
Great, re-open the issue if there is something else!
