### ISSUE TITLE
unraid docker error since update, GLib-GIO-ERROR

### ISSUE THREAD

**Issue by jeffykronus** [jlesage/docker-filebot#41]
on Unraid docker it looks like the container updated and now has error 

(process:957): GLib-GIO-ERROR **: 02:30:31.801: Settings schema 'org.gnome.system.proxy' is not installed
Trace/breakpoint trap
[amc] Invoking AMC script...
[amc]
[amc] (process:1022): GLib-GIO-ERROR **: 02:30:36.512: Settings schema 'org.gnome.system.proxy' is not installed

Container freezes at that point. 
Any help would be great, have reinstalled container and still get this error.

**Comment by sm0kingm4n** [comment]
same problem here docker container in OpenmediaVault:
`today at 12:21 PM (process:480): GLib-GIO-ERROR **: 12:21:57.973: Settings schema 'org.gnome.system.proxy' is not installed
today at 12:21 PM Trace/breakpoint trap (core dumped)
today at 12:21 PM [cont-init.d] filebot.sh: exited 133.
today at 12:21 PM [services.d] stopping services
today at 12:21 PM [services.d] stopping s6-fdholderd...
today at 12:21 PM [cont-finish.d] executing container finish scripts...
today at 12:21 PM [cont-finish.d] done.
today at 12:21 PM [s6-finish] syncing disks.
today at 12:21 PM [s6-finish] sending all processes the TERM signal.
today at 12:22 PM [s6-finish] sending all processes the KILL signal and exiting.
today at 12:21 PM Container stopped`

any workaround/fix/solution to this issue would be greatly appreciated,

**Comment by alexmacdonald5290** [comment]
Not a fix as such but downgrading to the previous release worked for me.

**Comment by jlesage** [comment]
Can you try to run `docker exec <container name> add-pkg gsettings-desktop-schemas` while the container is running ?
Then restart the container.

**Comment by jlesage** [comment]
A new image with the fix is now available.  Let me know if you still have problems.
