### ISSUE TITLE
Server disconnected (code:1006)

### ISSUE THREAD

**Issue by flammable-gel** [jlesage/docker-filebot#44]
Hi,
I'm stucked with this error: Server disconnected (code:1006).

![Screenshot (30)_LI](https://user-images.githubusercontent.com/73902579/98017357-6b5c2900-1dff-11eb-83ed-c06b886ad240.jpg)

In the log folder I get this error, don't know it means.

`[error] 689#689: *7 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.201, server: , request: "GET /websockify HTTP/1.1", upstream: "http://127.0.0.1:5900/websockify", host: "192.168.1.200:5801"`

Hope someone can help me,
Thanks

**Comment by jlesage** [comment]
Try to clear your browser's cache.

**Comment by flammable-gel** [comment]
Clearing the browser cache didn't help me, however with private browsing mode I solved it. It's probably a problem with my browser, with Ipad I have no issue. Thanks for your help.

**Comment by jlesage** [comment]
If it's working in private mode, it's a cache issue.  Make sure to also clear any storage data.

**Comment by jlesage** [comment]
Closing this issue, please re-open if needed.
