### ISSUE TITLE
Using docker-compose yields 'ERROR: Cannot locate specified Dockerfile: Dockerfile'

### ISSUE THREAD

**Issue by zzyzx-dc** [jlesage/docker-filebot#47]
Sorry if I'm making a rookie mistake. I'm using the following docker-compose.yml:

> version: '3'
> services:
>   filebot:
>     image: jlesage/filebot
>     build: .
>     ports:
>       - "5800:5800"
>     environment:
>       - USER_ID=1000
>       - GROUP_ID=1000
>     volumes:
>       - "/docker/appdata/filebot:/config:rw"
>       - "$HOME:/storage:rw"
>       - "/mnt/usb:/usb:rw"

I tried to specify the Dockerfile but that did not work.

**Comment by jlesage** [comment]
I guess you compose file is properly indented ? Which commands are you using ?  It should be something like:
```
docker-compose pull
docker-compose up
```

**Comment by justpeterpan** [comment]
Late reply but deleting the line 'build: .' from your docker-compose.yml will fix this.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
