### ISSUE TITLE
Filebot: site can't be reached

### ISSUE THREAD

**Issue by hazyitsm** [jlesage/docker-filebot#5]
I'm running the filebot container on the same Ubuntu 18.04 system that is running your makemkv container, as well as a bunch of other utility containers (hassio, node-red, mosquitto, Portainer...). Since Makemkv already uses port 5800, I've set Filebot to use a few different ports. Each time the url with the port at the end says the site can't be reached. Makemkv works like a champ trying it at the same time.

The ports I've tried: 5850, 5900, 5500

I assume I'm missing something blindingly obvious. I'm starting the container using the Quick Start settings, with only the port # changed.

docker run -d \
    --name=filebot \
    -p 5500:5500 \
    -v /docker/appdata/filebot:/config:rw \
    -v $HOME:/storage:rw \
    jlesage/filebot

The container starts up fine and stays running, per Portainer

Container log from Portainer:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 00-app-niceness.sh: executing... ,
[cont-init.d] 00-app-niceness.sh: exited 0.,
[cont-init.d] 00-app-script.sh: executing... ,
[cont-init.d] 00-app-script.sh: exited 0.,
[cont-init.d] 00-app-user-map.sh: executing... ,
[cont-init.d] 00-app-user-map.sh: exited 0.,
[cont-init.d] 00-clean-logmonitor-states.sh: executing... ,
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.,
[cont-init.d] 00-clean-tmp-dir.sh: executing... ,
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.,
[cont-init.d] 00-set-app-deps.sh: executing... ,
[cont-init.d] 00-set-app-deps.sh: exited 0.,
[cont-init.d] 00-set-home.sh: executing... ,
[cont-init.d] 00-set-home.sh: exited 0.,
[cont-init.d] 00-take-config-ownership.sh: executing... ,
[cont-init.d] 00-take-config-ownership.sh: exited 0.,
[cont-init.d] 00-xdg-runtime-dir.sh: executing... ,
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.,
[cont-init.d] 10-certs.sh: executing... ,
[cont-init.d] 10-certs.sh: exited 0.,
[cont-init.d] 10-cjk-font.sh: executing... ,
[cont-init.d] 10-cjk-font.sh: exited 0.,
[cont-init.d] 10-nginx.sh: executing... ,
[cont-init.d] 10-nginx.sh: exited 0.,
[cont-init.d] 10-vnc-password.sh: executing... ,
[cont-init.d] 10-vnc-password.sh: exited 0.,
[cont-init.d] 10-web-index.sh: executing... ,
[cont-init.d] 10-web-index.sh: exited 0.,
[cont-init.d] filebot.sh: executing... ,
[cont-init.d] filebot.sh: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] starting s6-fdholderd...,
[services.d] starting nginx...,
[nginx] starting...,
[services.d] starting certsmonitor...,
[services.d] starting xvfb...,
[xvfb] starting...,
[certsmonitor] disabling service: secure connection not enabled.,
[services.d] starting statusmonitor...,
[statusmonitor] no file to monitor: disabling service...,
s6-svwait: fatal: timed out,
[services.d] starting logmonitor...,
[services.d] starting openbox...,
[logmonitor] no file to monitor: disabling service...,
[openbox] starting...,
[services.d] starting x11vnc...,
[services.d] starting app...,
[x11vnc] starting...,
[app] starting FileBot...,
05/08/2019 22:04:49 passing arg to libvncserver: -rfbport,
05/08/2019 22:04:49 passing arg to libvncserver: 5900,
05/08/2019 22:04:49 passing arg to libvncserver: -rfbportv6,
05/08/2019 22:04:49 passing arg to libvncserver: -1,
05/08/2019 22:04:49 passing arg to libvncserver: -httpportv6,
05/08/2019 22:04:49 passing arg to libvncserver: -1,
05/08/2019 22:04:49 passing arg to libvncserver: -desktop,
05/08/2019 22:04:49 passing arg to libvncserver: FileBot,
05/08/2019 22:04:49 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 804,
05/08/2019 22:04:49 Using X display :0,
05/08/2019 22:04:49 rootwin: 0x43 reswin: 0x400001 dpy: 0x663a19e0,
05/08/2019 22:04:49 ,
05/08/2019 22:04:49 ------------------ USEFUL INFORMATION ------------------,
[services.d] done.,
05/08/2019 22:04:49 X DAMAGE available on display, using it for polling hints.,
05/08/2019 22:04:49   To disable this behavior use: '-noxdamage',
05/08/2019 22:04:49 ,
05/08/2019 22:04:49   Most compositing window managers like 'compiz' or 'beryl',
05/08/2019 22:04:49   cause X DAMAGE to fail, and so you may not see any screen,
05/08/2019 22:04:49   updates via VNC.  Either disable 'compiz' (recommended) or,
05/08/2019 22:04:49   supply the x11vnc '-noxdamage' command line option.,
05/08/2019 22:04:49 X COMPOSITE available on display, using it for window polling.,
05/08/2019 22:04:49   To disable this behavior use: '-noxcomposite',
05/08/2019 22:04:49 ,
05/08/2019 22:04:49 Wireframing: -wireframe mode is in effect for window moves.,
05/08/2019 22:04:49   If this yields undesired behavior (poor response, painting,
05/08/2019 22:04:49   errors, etc) it may be disabled:,
05/08/2019 22:04:49    - use '-nowf' to disable wireframing completely.,
05/08/2019 22:04:49    - use '-nowcr' to disable the Copy Rectangle after the,
05/08/2019 22:04:49      moved window is released in the new position.,
05/08/2019 22:04:49   Also see the -help entry for tuning parameters.,
05/08/2019 22:04:49   You can press 3 Alt_L's (Left "Alt" key) in a row to ,
05/08/2019 22:04:49   repaint the screen, also see the -fixscreen option for,
05/08/2019 22:04:49   periodic repaints.,
05/08/2019 22:04:49 GrabServer control via XTEST.,
05/08/2019 22:04:49 ,
05/08/2019 22:04:49 Scroll Detection: -scrollcopyrect mode is in effect to,
05/08/2019 22:04:49   use RECORD extension to try to detect scrolling windows,
05/08/2019 22:04:49   (induced by either user keystroke or mouse input).,
05/08/2019 22:04:49   If this yields undesired behavior (poor response, painting,
05/08/2019 22:04:49   errors, etc) it may be disabled via: '-noscr',
05/08/2019 22:04:49   Also see the -help entry for tuning parameters.,
05/08/2019 22:04:49   You can press 3 Alt_L's (Left "Alt" key) in a row to ,
05/08/2019 22:04:49   repaint the screen, also see the -fixscreen option for,
05/08/2019 22:04:49   periodic repaints.,
05/08/2019 22:04:49 ,
05/08/2019 22:04:49 XKEYBOARD: number of keysyms per keycode 7 is greater,
05/08/2019 22:04:49   than 4 and 51 keysyms are mapped above 4.,
05/08/2019 22:04:49   Automatically switching to -xkb mode.,
05/08/2019 22:04:49   If this makes the key mapping worse you can,
05/08/2019 22:04:49   disable it with the "-noxkb" option.,
05/08/2019 22:04:49   Also, remember "-remap DEAD" for accenting characters.,
05/08/2019 22:04:49 ,
05/08/2019 22:04:49 X FBPM extension not supported.,
Xlib:  extension "DPMS" missing on display ":0".,
05/08/2019 22:04:49 X display is not capable of DPMS.,
05/08/2019 22:04:49 --------------------------------------------------------,
05/08/2019 22:04:49 ,
05/08/2019 22:04:49 Default visual ID: 0x21,
05/08/2019 22:04:49 Read initial data from X display into framebuffer.,
05/08/2019 22:04:49 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120,
05/08/2019 22:04:49 ,
05/08/2019 22:04:49 X display :0 is 32bpp depth=24 true color,
05/08/2019 22:04:49 ,
05/08/2019 22:04:49 Listening for VNC connections on TCP port 5900,
05/08/2019 22:04:49 ,
05/08/2019 22:04:49 Xinerama is present and active (e.g. multi-head).,
05/08/2019 22:04:49 Xinerama: number of sub-screens: 1,
05/08/2019 22:04:49 Xinerama: no blackouts needed (only one sub-screen),
05/08/2019 22:04:49 ,
05/08/2019 22:04:49 fb read rate: 1941 MB/sec,
05/08/2019 22:04:49 fast read: reset -wait  ms to: 10,
05/08/2019 22:04:49 fast read: reset -defer ms to: 10,
05/08/2019 22:04:49 The X server says there are 10 mouse buttons.,
05/08/2019 22:04:49 screen setup finished.,
05/08/2019 22:04:49 ,
,
The VNC desktop is:      91f7117668fe:0,,
0,
,
******************************************************************************,
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?,
,
The scheme stores pixel data offscreen on the VNC viewer side for faster,
retrieval.  It should work with any VNC viewer.  Try it by running:,
,
    x11vnc -ncache 10 ...,
,
One can also add -ncache_cr for smooth 'copyrect' window motion.,
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching,
,
FileBot 4.8.5 (r6224),
JNA Native: 5.2.2,
MediaInfo: 18.08.1,
p7zip: p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz (306C3),ASM,AES-NI),
unrar: UNRAR 5.61 freeware,
Chromaprint: fpcalc version 1.4.3,
Extended Attributes: OK,
Unicode Filesystem: OK,
Script Bundle: 2019-05-15 (r565),
Groovy: 2.5.6,
JRE: OpenJDK Runtime Environment 1.8.0_201,
JVM: 64-bit OpenJDK 64-Bit Server VM,
CPU/MEM: 4 Core / 1 GB Max Memory / 26 MB Used Memory,
OS: Linux (amd64),
HW: Linux 91f7117668fe 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 Linux,
DATA: /config,
Package: DOCKER,
License: UNREGISTERED,
Done ヾ(＠⌒ー⌒＠)ノ,
Prism pipeline init order: sw ,
Using java-based Pisces rasterizer,
Using dirty region optimizations,
Not using texture mask for primitives,
Not forcing power of 2 sizes for textures,
Using hardware CLAMP_TO_ZERO mode,
Opting in for HiDPI pixel scaling,
*** Fallback to Prism SW pipeline,
Prism pipeline name = com.sun.prism.sw.SWPipeline,
(X) Got class = class com.sun.prism.sw.SWPipeline,
Initialized prism pipeline: com.sun.prism.sw.SWPipeline,
 vsync: true vpipe: false,

**Comment by jlesage** [comment]
The port mapping should be set with `-p 5500:5800` instead of `-p 5500:5500`.

**Comment by hazyitsm** [comment]
So glad it was something simple. That did it. Thank you!
