### ISSUE TITLE
Server disconnected while using reverse proxy

### ISSUE THREAD

**Issue by saltyspi** [jlesage/docker-filebot#51]
Hi,
I've just installed and configured the Filebot container and everything working fine, except the proxy.
If I'm using http://filebot.mydomain.com:5800, the server is see as online but if I try httpS://filebot.mydomain.com it doesn't.
The error is "Server disconnected (code 1006)".

I'm running everything on a Synology, so I use the integrated reverse proxy with these informations
-Source-
protocol: https
hostname: filebot.mydomain.com
port: 443
HTTP/2 enabled

-destination-
protocol: http
hostname: localhost
port: 5800

I'm already using this method for other Docker containers without issue, so I don't understand why it doesn't work.
Could you help me please?

**Comment by jlesage** [comment]
You need to enable WebSocket support.  See https://mlohr.com/websockets-for-synology-dsm/

**Comment by saltyspi** [comment]
Hi,
Thanks for your answer. It worked well !
