### ISSUE TITLE
Seasonal Anime sorted with TheTVDB 

### ISSUE THREAD

**Issue by xlmktvz** [jlesage/docker-filebot#55]
Hi, 
first of all, I don’t know if this is really an issue which can be easily fixed/solved or just some general “filebot limitation” itself. 

**Following Situation:** 
I use fieldboot to “watche” my Jdownloader folder to sort my downloads to my Plex media folders (Movies, TV Shows, Anime)

I have set up a “watched” folder with a subfolder “Anime”. So, everything within the “Anime” folder should be forced to use AniDB and sorted in “Anime” folder of Plex. 

In general, this works well! But, for seasonal animes (e.g. Attack on Titan, My Hero Academia etc.) even though put in the sub-path “Watched/Anime/” they get sorted by “TheTVDB” and thus to my plex output folder “TV Shows”. 

Is there a way to “force” Anime, independent of AniDB or TheTVDB to a certain output directory?

Thank You!

**Comment by jlesage** [comment]
The container is using the AMC script of FileBot.  I would suggest that you look at the FileBot forum to see if there is anything that can help you.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
