### ISSUE TITLE
feature request: add ability to disable gui and just have watcher script running

### ISSUE THREAD

**Issue by Mearman** [jlesage/docker-filebot#58]
Not sure if this is possible. But I'd love to have the GUI and VNC server disabled most of the time.
Might be wrong but I don't see anything in the docs that looks like it's currently possible.

**Comment by jlesage** [comment]
Yes, this is something that will be feasible in the future: it would be possible to disable the UI using an environment variable.

**Comment by jlesage** [comment]
This is now supported with the latest image.
