### ISSUE TITLE
AMC not moving files after environment variable updated to "move"

### ISSUE THREAD

**Issue by lynchpinhags** [jlesage/docker-filebot#59]
Hi all,

I recently got this container up and running on my Synology via Docker and it's going well (your documentation is awesome, thank you!). I want to expressly use it for AMC, and I have permissions set correctly and mapped to PGID and PUID in variables. I ran it with some dry runs to test and the log indicated it was matching media well, so I changed the environment variable to "move", and the script has created folders where the media should be moved to, but doesn't move and rename the media files.

Censored log as follows:

[amc] Input: /watch/movie_filename.mkv
[amc] Group: {Movie Actual Name} => [movie_filename.mkv]
[amc] Rename movies using [TheMovieDB]
[amc] Auto-detect movie from context [/watch/movie_filename.mkv]
[amc] [MOVE] from [/watch/movie_filename.mkv] to [/output/Movies/Movie Actual Name.mkv]
[amc] [MOVE] from [/watch/movie_filename.mkv] to [/output/Movies/Movie Actual Name.mkv.mkv] failed due to I/O error [Access Denied: /watch/movie_filename.mkv]
[amc] Processed 0 files

![image](https://user-images.githubusercontent.com/32887917/124340702-3dc9b880-dbf6-11eb-80db-bd9ca425d31a.png) (these match the UID and GID I got from SSHing into the Synology and checking the user's ID).

If it's creating the folder in the destination, then the write permission is OK I'm assuming for that folder, but it's not able to move a file from the watch directory. The permissions on both directories for the same user are identical. Is there anything else I may be missing?

**Comment by lynchpinhags** [comment]
Strangely, by updating the variable to "copy", it works as expected. But "move" does not. Any ideas?

Thanks!

**Comment by jlesage** [comment]
Looks like the container doesn't have write permission on the watch folder/file ?

Check the permissions and ownership of the folder on the Synology that you mapped to `/watch` in the container.

**Comment by lynchpinhags** [comment]
Thank you! Turns out there was another setting with permissions that I overlooked. All fixed.
