### ISSUE TITLE
not support chinese

### ISSUE THREAD

**Issue by xxzj990** [jlesage/docker-filebot#6]
How should I add Chinese support?

**Comment by jlesage** [comment]
You mean for the application itself?  I think the FileBot UI is only available in English.

**Comment by xxzj990** [comment]
@jlesage Not application, file name garbled.

![20190813191032](https://user-images.githubusercontent.com/5134154/62937097-26b13000-bdfe-11e9-85fb-b31abb168cef.png)

**Comment by jlesage** [comment]
Can you try to set the `ENABLE_CJK_FONT` environment variable to `1`?

**Comment by xxzj990** [comment]
@jlesage It works.Thanks!
