### ISSUE TITLE
List of environment variables for AMC

### ISSUE THREAD

**Issue by lynchpinhags** [jlesage/docker-filebot#60]
Hi all,

Per this thread: https://www.filebot.net/forums/viewtopic.php?f=13&t=12684&p=55064#p55064

I'm using this container for AMC and I'd like to add additional environment variables to control notifications via Pushbullet and also to handle archives (unrar + delete leftover files). Are these variables documented anywhere like the table on the https://github.com/jlesage/docker-filebot#environment-variables page?

Any help or advice would be great. Thanks!

**Comment by lynchpinhags** [comment]
Alternatively, do you have any guides on how to pass other AMC commands like unrar behaviour and Pushbullet notification to the container?

**Comment by jlesage** [comment]
Sorry for the late answer.

Do you already know how to achieve that with AMC?

Variables exists for basic stuff, but else there is the `AMC_CUSTOM_OPTIONS` variable that allows you to do anything you want.

**Comment by lynchpinhags** [comment]
That's okay! I don't know how to do that, sorry. If I set AMC_CUSTOM_OPTIONS in the variables section in the container set up, what format should I use for custom options? Say if I wanted to enable Pushbullet? Once I know the syntax to use I'm happy to have a crack at it. Thanks for your help!

**Comment by jlesage** [comment]
For the archive extraction, I think that AMC will do it automatically.

The supported AMC options are documented here: https://www.filebot.net/forums/viewtopic.php?t=215.  For Pushbullet, the option is `--def pushbullet=apikey`.  This is what you would put as the content of the `AMC_CUSTOM_OPTIONS` variable.

**Comment by lynchpinhags** [comment]
Thanks! This worked perfectly for Pushbullet.
