### ISSUE TITLE
The way to solve error code (Chinese/Japanese and so on...)

### ISSUE THREAD

**Issue by susundingkai** [jlesage/docker-filebot#61]
Copy font file (download or from Windows) to /usr/share/fonts in docker

**Comment by jlesage** [comment]
Setting the `ENABLE_CJK_FONT` environment variable doesn't work for you ?
https://github.com/jlesage/docker-filebot#environment-variables

**Comment by jlesage** [comment]
Closing issue, please reopen if needed.
