### ISSUE TITLE
Automated Media Center: Action.

### ISSUE THREAD

**Issue by jaschuu** [jlesage/docker-filebot#62]
Hello, can someone explain to me the differences for the options of the Automated Media Center: Action.
I understand test, copy and move, but what does symlink, hardlink, keeplink, duplicate and clone do???

thanks.

**Comment by jlesage** [comment]
Here is the doc about the actions:
https://www.filebot.net/forums/viewtopic.php?t=4915

**Comment by jaschuu** [comment]
thank you
