### ISSUE TITLE
How can you define multiple values for one environment variable?

### ISSUE THREAD

**Issue by lynchpinhags** [jlesage/docker-filebot#63]
Per this thread: https://github.com/jlesage/docker-filebot/issues/60

I'm using the AMC_CUSTOM_OPTIONS to utilise Pushbullet notifications (using "--def pushbullet=apikey").

However, I'd like to add another value for the same environment variable (to tell AMC to delete archives after extraction). The variables page won't let me add another instance of "AMC_CUSTOM_OPTIONS", so I was wondering if there was a way to add multiple entries for the same environment variable? Can I separate values with a comma or something similar?

Thanks!

**Comment by jlesage** [comment]
Yes you can use multiple arguments in `AMC_CUSTOM_OPTIONS `, separated by a space.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
