### ISSUE TITLE
Error invalid --security-opt 2

### ISSUE THREAD

**Issue by gcraenen** [jlesage/docker-filebot#64]
When brinigng up filebot in a larger docker-compose I'm getting this error:

ERROR: for filebot  Cannot create container for service filebot: invalid --security-opt 2: "/home/USER/docker/appdata/filebot:/config:rw"

This is the docker-compose I'm using:

#FileBot - File renamer
  filebot:
    image: jlesage/filebot:latest
    container_name: filebot
    restart: "no"
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    #ports:
      #- "$FILEBOT_PORT:5800"
    #volumes:
      #A *.psm license file is required in /config
      #https://github.com/jlesage/docker-filebot#installing-a-license
      - $DOCKERDIR/appdata/filebot:/config:rw
      - $DATADIR:/data/media
      - $DATADIR/downloads:/data/downloads
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
      UMASK: 022
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 960
      VNC_PASSWD: $FILEBOT_VNC_PASSWD
    labels:
      - "traefik.enable=true"
      #HTTP Routers
      - "traefik.http.routers.filebot-rtr.entrypoints=https"
      - "traefik.http.routers.filebot-rtr.rule=Host(`filebot.$DOMAINNAME0`)"
      #Middlewares
      - "traefik.http.routers.filebot-rtr.middlewares=chain-oauth@file"
      #HTTP Services
      - "traefik.http.routers.filebot-rtr.service=filebot-svc"
      - "traefik.http.services.filebot-svc.loadbalancer.server.port=5800"

**Comment by jlesage** [comment]
I guess the problem is that `#volumes:` is commented ?

**Comment by jlesage** [comment]
Closing issue.  Please re-open if needed.
