### ISSUE TITLE
Dconf error

### ISSUE THREAD

**Issue by Kopernikus1979** [jlesage/docker-filebot#65]
Hi,

This FileBot docker seems to be working fine, however in the log I have:

`(process:995): dconf-CRITICAL **: 12:12:37.781: unable to create file '/tmp/run/user/app/dconf/user': Permission denied. dconf will not work properly.`

Got this answer from the developer rednoah:

> Based on the logs, my best guess is that those dconf warning messages are related to networking and perhaps proxy auto-config. You may need to ask the author to explicitly enable / disable proxy support. It probably can't work inside the container anyway.

**Comment by jlesage** [comment]
This is fixed in latest Docker image (v1.13.0).
