### ISSUE TITLE
remote execution from jdownload container

### ISSUE THREAD

**Issue by no-Legend** [jlesage/docker-filebot#66]
Hi,

is there a way to call the amc script from an other container?
When I was running downloader natively on my system, I was running a script after the extraction was finished.

This is how I use the event trigger by jd.
`[{"eventTrigger":"ON_ARCHIVE_EXTRACTED", "enabled":true, "name":"FileBot", "script":"var amcFile = \"/volume1/video/filebot.sh\";var path = archive.getFolder(); callAsync(function() {}, amcFile, path);", "eventTriggerSettings":{}, "id":}]`

And this is the scirpt I normally run.
```
#!/bin/sh
##FileBot benötigt diese Variablen
##/bin/mkdir /volume1/video/Downloads/videos/testordner
LOG="/volume1/amc.log"
EXC="/volume1/amc.txt"
SERIEN="/volume1/video/Serien/{n}/{s}/{n}.{s00e00} - {t} ({y}) {vf}"
FILME="/volume1/video/Filme/{n} ({y}) {source}({vf}@{vc}) [{rating}]/{n} ({y}) {source}({vf}@{vc}) [{rating}]"
##UNSORTIERT="/path/{file.structurePathTail}" ### Wenn Filebot mal etwas nicht zuordnen kann, dann kannst du es in einen seperaten Ordner verschieben lassen, dann bleibt es im Downloadordner übersichtlich.
##FileBot ausführen
/var/packages/filebot/target/filebot.sh -script fn:amc --lang de --log-file $LOG --action move "$1" --def "seriesFormat=$SERIEN" "movieFormat=$FILME" "animeFormat=$ANIME" "unsortedFormat=$UNSORTIERT" -non-strict --def unsorted=y "artwork=y" --def clean=y
## Aufräumen, --def root löscht den Unterordner mit
/var/packages/filebot/target/filebot.sh -script fn:cleaner "$1" --def root=y
```

**Comment by jlesage** [comment]
This container supports automatic AMC invocation using a watch folder: https://github.com/jlesage/docker-filebot#automated-media-center-amc

Is this what you are looking for ?

**Comment by no-Legend** [comment]
Sorry for my late answers. 
no that isn’t what I’m looking for.
As I was using the nativ installation, the script waits until the extraction is finished.
Afterwards the script calls filebot and gives the folder name to the script any only this folder is executed.
At the moment it is only possible to call the script to execute not to give the folder to run in.

pherhaps this an feature for a further release (node version)?

Cheers Robert

**Comment by jlesage** [comment]
So you want to use the filebot binary inside the container like the native one you had ?  And you want filebot binary to be called from JDownloader running in another container ?  This doesn't seem possible.  However, you should be able to reproduce the same behaviour by using the watch folder functionality.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
