### ISSUE TITLE
history.xml not being read

### ISSUE THREAD

**Issue by Nexius2** [jlesage/docker-filebot#68]
Hello,
it's not the first time it happens to me, history.xml looks like it is filled as I see last changes made to it, but when I open it in filebot, it says 0 changes.
if I delete the file, everything works again.
and after a while, the issue comes back.
maybe a size problem??? mine is 4.1 Mb
thanks

**Comment by jlesage** [comment]
This seems to be an issue with FileBot itself.  Did you also reported the issue on the FileBot forum ?

**Comment by jlesage** [comment]
Did you find an answer to your issue ?
I'm closing this issue, but please re-open if needed.
