### ISSUE TITLE
Crashing with OpenSubtitles Environment Variables Set

### ISSUE THREAD

**Issue by speedybutters** [jlesage/docker-filebot#69]
[filebot_logs.zip](https://github.com/jlesage/docker-filebot/files/7896109/filebot_logs.zip)

Hi,

It looks like using OpenSubtitles environment variables is causing the container to crash; I've attached logs with the variables set and unset in case that's helpful.

I've also reset my password on opensubtitles.org and confirmed it works, and tried creating an account opensubtitles.com but the container still crashes with the same error.

I'm assuming based on the timing it's something to do with the opensubtitles.org hack? https://forum.opensubtitles.org/viewtopic.php?t=17685

Also found this: https://www.filebot.net/forums/viewtopic.php?f=10&p=56644 which suggests it's an issue with filebot versions below 4.9.5 and there's no workaround. 4.9.5 is in beta at the moment.

Not a specific problem with the container, just wanted to let you know and offer my services as a guinea pig if you wanted to test the 4.9.5 beta!

Thank you for your awesome work

**Comment by jlesage** [comment]
According to the thread you linked, a fix has been made for the FileBot cli.  So having credentials set should no longer prevent the container from starting.

Problem probably remains for the UI.  However, with the latest container image, you can now easily test the beta version of FileBot.  See https://github.com/jlesage/docker-filebot#using-a-beta-version.
