### ISSUE TITLE
Request: To be able to choose the lang

### ISSUE THREAD

**Issue by imTHAI** [jlesage/docker-filebot#70]
Hello,

I'm using ur docker since long time, since I use unraid.
I'd like to ask: would it be possible to change de default language used to rename ? 
To set it with en ENV variable like the others parameters, for example.

Same in [this one](https://github.com/mondediefr/docker-rutorrent)
FILEBOT_LANG | Set your language | optional | fr

Thank you

**Comment by jlesage** [comment]
This is now implemented in latest Docker image (v1.13.0), vi at the `AMC_LANG` variable.
The unRAID template also has a dedicated setting.
