### ISSUE TITLE
Request: Possible to switch to quacamole or noVNC

### ISSUE THREAD

**Issue by coltonshipley** [jlesage/docker-filebot#72]
Any chance it would be possible to switch your gui container to guacamole or noVNC instead of the vnc used? To allows you to resize windows and if you make them maximized, it auto scales with the browser.

linuxserver.io firefox container and ich777 Krusader images are great examples in the unraid store.

**Comment by jlesage** [comment]
The container already uses noVNC (noVNC is the VNC client).  The fact that the window app doesn't resize to the browser's window is due to the VNC server used inside the container.
I'm already working on integrating a new VNC server that will support this feature.

**Comment by jlesage** [comment]
Remove resizing is now supported with the latest image.
