### ISSUE TITLE
Can't select root folder for media to rename

### ISSUE THREAD

**Issue by PepsiBlue14** [jlesage/docker-filebot#73]
I'm running Filebot in unRAID, which updates the container as they are provided. Today, while trying to select a "movies" root folder to rename and export, the app will open into that folder, and expect me to select a file. If a folder is selected within the root "movies" folder, it'll open it. I've restarted the app and the problem still exists. In short, I can't select a root folder for Filebot to review, rename files, and export them.

**Comment by aaddaammgg** [comment]
For me, it is all folders. It will keep expanding the folder until I hit a file.

**Comment by jlesage** [comment]
I also reproduce the problem.

I reported the issue on FileBot forum: https://www.filebot.net/forums/viewtopic.php?f=11&t=13073

**Comment by jlesage** [comment]
Fixed in latest Docker image (`v1.14.0`).
