### ISSUE TITLE
Custom Filebot URL Variable

### ISSUE THREAD

**Issue by coltonshipley** [jlesage/docker-filebot#74]
Would it be possible to add in something like ENV FILEBOT_URL so we can speicify a custom url for a portable version of filebot?

I tried buiding an image from your Dockerfile but It pauses durin the unrar stuff at the top and never continues. Something about an empty git repo.

Just an override for a custom url would be awesome so you can just paste in like https://github.com/barry-allen07/FB-Mod/releases/download/4.8.5/FileBot_4.8.5-Linux-Portable.tar.xz

**Comment by jlesage** [comment]
Yes it's possible to use a beta/custom version.  See https://github.com/jlesage/docker-filebot#using-a-beta-version

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
