### ISSUE TITLE
The Chinese characters are garbled

### ISSUE THREAD

**Issue by Nothend** [jlesage/docker-filebot#76]
Hello, big brother, I am a friend from China, thank you for providing such a good tool, thank you very much! I have a problem here, that is, most of my movie names are in Chinese. When using your filebot tool, I found that the Chinese characters are all garbled. Please tell me, how to solve it? Below is the picture, thanks again!

![image](https://user-images.githubusercontent.com/73117056/173263331-c919a7c8-d9b7-498b-8d28-4ae7921bfb4e.png)

![image](https://user-images.githubusercontent.com/73117056/173263389-ed123177-4b06-4cb1-a7ea-e109c3cd626f.png)

and I set the ENABLE_CJK_FONT environment variable to 1

![image](https://user-images.githubusercontent.com/73117056/173264725-39a98bb4-3b20-4412-9142-f0472009bc71.png)

**Comment by Nothend** [comment]
Sorry, it took effect after restarting

**Comment by jlesage** [comment]
Glade to know that you fixed the issue!
