### ISSUE TITLE
Running two Of your Docker Containers at once

### ISSUE THREAD

**Issue by darkangelvenom** [jlesage/docker-filebot#77]
I am trying to run your MakeMKV and Filebot containers at the same time and your docs say that the internal port for both must be 5800. When I run them both I can't connect to both even with differing host ports. This is definitely a "noob" issue, but I would appreciate any guidance you could give me, given this is my first foray into docker

**Comment by jlesage** [comment]
Assuming you are using the default bridge network type, you need to map port 5800 of the container to a different port on the host.  This is done via the `-p` parameter of the `docker run` command.

**Comment by darkangelvenom** [comment]
Turns out I am in fact dumb and had forgot to allow it through UFW lol. Thanks for answering tho
