### ISSUE TITLE
Automatic processing

### ISSUE THREAD

**Issue by skylord123** [jlesage/docker-filebot#8]
I've been using coppit's filebot contianer (https://hub.docker.com/r/coppit/filebot/) for a while now. The automatic processing is key for me and I am curious how I would accomplish that with this container.

In coppit's container there is a `filebot.sh` file that is generated inside the `/config` folder that allows you to edit various settings for automatic processing. Here is the default file that gets generated if one doesn't exist:
https://github.com/coppit/docker-filebot/blob/master/filebot.sh

You set the ENV variables `INPUT_DIR` and `OUTPUT_DIR` and then it uses this script for doing the automatic processing.

Can we get this support for this container? I wanted to switch to your container so I could use my license and the newer version but this is something that is a necessity for me.

Thanks!

**Comment by jlesage** [comment]
Support is finally here, in image version `1.3.0`.

Note that implementation differs from coppit's container.  Make sure to read documentation at
https://github.com/jlesage/docker-filebot#automated-media-center-amc

**Comment by skylord123** [comment]
Good job! Thanks a ton! :)
