### ISSUE TITLE
DNS error in activating license

### ISSUE THREAD

**Issue by parthmodi** [jlesage/docker-filebot#83]
Recently I've had an issue where the docker container cannot reach the hosts to activate license. After trying to delete the container and image and pull it again, It will no longer connect to the api server. I see this line in the logs:

Network Error: DNS server failed to resolve IP for host name: api.filebot.net

I confirmed that my host machine can ping api.filebot.net - so it can reach it. What's the best way to resolve this issue?

**Comment by jlesage** [comment]
Can you also ping from inside the container ?

```
docker exec <container name> ping api.filebot.net
```

**Comment by parthmodi** [comment]
Hi, Yes I can. 

`PS J:\DockerDesktop\main_stack> docker exec filebot ping api.filebot.net
PING api.filebot.net (172.67.141.139): 56 data bytes
64 bytes from 172.67.141.139: seq=0 ttl=36 time=24.165 ms
64 bytes from 172.67.141.139: seq=1 ttl=36 time=11.128 ms
64 bytes from 172.67.141.139: seq=2 ttl=36 time=10.244 ms
64 bytes from 172.67.141.139: seq=3 ttl=36 time=11.321 ms
64 bytes from 172.67.141.139: seq=4 ttl=36 time=5.110 ms
64 bytes from 172.67.141.139: seq=5 ttl=36 time=10.401 ms
64 bytes from 172.67.141.139: seq=6 ttl=36 time=15.693 ms
64 bytes from 172.67.141.139: seq=7 ttl=36 time=5.585 ms
64 bytes from 172.67.141.139: seq=8 ttl=36 time=5.509 ms
64 bytes from 172.67.141.139: seq=9 ttl=36 time=6.014 ms
64 bytes from 172.67.141.139: seq=10 ttl=36 time=8.415 ms
64 bytes from 172.67.141.139: seq=11 ttl=36 time=9.948 ms
64 bytes from 172.67.141.139: seq=12 ttl=36 time=10.237 ms
64 bytes from 172.67.141.139: seq=13 ttl=36 time=8.189 ms
64 bytes from 172.67.141.139: seq=14 ttl=36 time=11.035 ms
64 bytes from 172.67.141.139: seq=15 ttl=36 time=9.612 ms
64 bytes from 172.67.141.139: seq=16 ttl=36 time=7.623 ms
64 bytes from 172.67.141.139: seq=17 ttl=36 time=8.606 ms
64 bytes from 172.67.141.139: seq=18 ttl=36 time=11.341 ms`

**Comment by jlesage** [comment]
Can you share the container's log ?
```
docker logs filebot
```

**Comment by parthmodi** [comment]
Not sure how to explain it. But Upon starting it again, it began to work. Been ahving this issue for 2 weeks. I'll go ahead and mark this closed.

**Comment by jlesage** [comment]
Ok perfect, re-open if needed.
