### ISSUE TITLE
Will you update the version of your Filebot to v5?

### ISSUE THREAD

**Issue by Speedmod88** [jlesage/docker-filebot#85]
Hi, just to want to know if you will update your filebot version from your docker to the newer one? Filebot v5.0.0

Thanks

**Comment by jlesage** [comment]
Yes!  Thanks for reporting, I didn't see this update.

**Comment by jlesage** [comment]
New image available!

**Comment by Speedmod88** [comment]
nice thanks a lot :)

**Comment by Speedmod88** [comment]
FileBot 5.0.1
• Fix the TheTVDB search issues ([1](https://www.filebot.net/forums/viewtopic.php?t=13621))
• Fix TVmaze lookup issues ([2](https://www.filebot.net/forums/viewtopic.php?t=13622))
• Fix series auto-selection issues ([3](https://www.filebot.net/forums/viewtopic.php?t=13625))

**Comment by Speedmod88** [comment]
they release a new version with fix issues

**Comment by jlesage** [comment]
The image has been updated with FileBot 5.0.1.
