### ISSUE TITLE
the text has broken...

### ISSUE THREAD

**Issue by gerberanub** [jlesage/docker-filebot#87]
the text has broken.. i cant read of it
 is there any option to change character set to utf-8 or something ? 
![화면 캡처 2023-04-03 010928](https://user-images.githubusercontent.com/50837748/229365188-fd746868-509e-4190-bc6f-186a379ee615.png)

**Comment by jlesage** [comment]
These were showing correctly before ?
Can you show how they suppose to look ?

**Comment by gerberanub** [comment]
> 

nope,   it has broken from first .
it has to show like below.  it is korean words.
where can i change language setting to korean ?
thanks
![화면 캡처 2023-04-04 223952](https://user-images.githubusercontent.com/50837748/229811172-e73512f8-0614-4644-bf5c-7130c5a450d8.png)

**Comment by jlesage** [comment]
Ok, you need to set the `ENABLE_CJK_FONT` variable.
See https://github.com/jlesage/docker-filebot#environment-variables

**Comment by gerberanub** [comment]
> Ok, you need to set the `ENABLE_CJK_FONT` variable. See https://github.com/jlesage/docker-filebot#environment-variables

working.  thank you so much.

**Comment by jlesage** [comment]
Great!  I'm closing this issue.
