### ISSUE TITLE
After 5.0.1 all items in amc log says Failed to parse media property: CreationTime:

### ISSUE THREAD

**Issue by tortofe01** [jlesage/docker-filebot#88]
After 5.0.1 all items in amc log says Failed to parse media property: CreationTime:  and nothing is renamed and nothing moves anymore even though it was working before then.

[amc         ] # A fatal error has been detected by the Java Runtime Environment:
[amc         ] #
[amc         ] #  SIGSEGV (0xb) at pc=0x0000159372f37770, pid=918, tid=314
[amc         ] #
[amc         ] # JRE version: OpenJDK Runtime Environment (17.0.6+10) (build 17.0.6+10-alpine-r0)
[amc         ] # Java VM: OpenJDK 64-Bit Server VM (17.0.6+10-alpine-r0, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
[amc         ] # Problematic frame:
[amc         ] # C  [libmediainfo.so+0x131030]  ZenLib::BitStream_LE::Get(unsigned long)+0x50
[amc         ] #
[amc         ] # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
[amc         ] #

**Comment by jlesage** [comment]
Are you able to reproduce with the same file every time ?  Do you also see the crash when using the UI ?

Can you try to reproduce with open source or free video samples, like https://durian.blender.org/download/ ?

**Comment by tortofe01** [comment]
I will try that in just a bit.  Several other people I know are having the exact same issue though on their separate unraid setups with 5.0.1

Thanks for all of your time!  Will get back to you in a bit.

**Comment by jlesage** [comment]
I was able to reproduce.  I had to try at least 5 times on the same file before seeing the crash.

**Comment by tortofe01** [comment]
Is there anyway to revert back to an older version while waiting for a potential fix?

**Comment by jlesage** [comment]
Yes, you can use a specific version of the image by using the associated Docker image tag: https://hub.docker.com/r/jlesage/filebot/tags

**Comment by jlesage** [comment]
The crash was caused by a component of the MediaInfo library.

See https://github.com/MediaArea/MediaInfoLib/issues/1730

**Comment by jlesage** [comment]
New image with the fix is now available !
