### ISSUE TITLE
It is possible choose between strict and non-strict mode?

### ISSUE THREAD

**Issue by ikarlo** [jlesage/docker-filebot#9]
Hi,
I noticed that you can not choose between strict and non-strict mode because the latter is hard coded in container command line FileBot's AMC script.

Is there any shortcut to enable strict mode?
I thought about using "AMC_CUSTOM_OPTIONS" variabile but I don't know if it could create a conflict.

Thanks

**Comment by jlesage** [comment]
Thanks for raising this.  With the latest container image version, I made this option configurable.  See the `AMC_MATCH_MODE` variable.

**Comment by ikarlo** [comment]
Perfect, thank you so much.

**Comment by nolazybits** [comment]
Hello there,

Runing the latest image
sha256:4071b36d131266aa688c200faca0c13498ec1fcfd0f9e44679b3f4bb8f90bb52

```
root@nolazybits-omv1:~# docker exec -it filebot bash
bash-4.4# echo $AMC_MATCH_MODE
opportunistic
```

This is the message in my logs
`* Consider using -non-strict to enable search by name and opportunistic matching`

Thanks

**Comment by jlesage** [comment]
Can you share more log messages to get the context ?
