### ISSUE TITLE
[Feature request] Set movieDB and seriesDB in the environment

### ISSUE THREAD

**Issue by update-freak** [jlesage/docker-filebot#94]
### Idea

Hi,
is it possible to set

- movieDB=TheMovieDB
- seriesDB=TheTVDB

in the environment or is this the default setting?
If not then this could be an improvement to add this option.

**Comment by jlesage** [comment]
You should be able to set these parameters via the `AMC_CUSTOM_OPTIONS` environment variable.  For example, `AMC_CUSTOM_OPTIONS=--def movieDB=TheMovieDB`.

**Comment by ripsnortntear** [comment]
yes this is possible but not possible down the line farther with
--def movieDB=TheMovieDB seriesDB=TheMovieDB::TV

the : mess up the yaml unless its in " " but that has to be supported on the back end of the Dockerfile

**Comment by update-freak** [comment]
thanks. I for the info. I will close this ticket
