### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by hot22shot** [jlesage/docker-filebot#96]
### Idea

Hello,

Could you update filebot to the latest version ? It fix a bug with thetvdb (https://www.filebot.net/forums/viewtopic.php?p=59987)

Thanks !

**Comment by jlesage** [comment]
Hi, the latest stable and official version (5.0.3) is already the one integrated into the container.

If you talk about the latest BETA, you may install it using the documented instruction: https://github.com/jlesage/docker-filebot#using-a-beta-version

**Comment by hot22shot** [comment]
Thanks I'll try that

**Comment by gurabli** [comment]
> Hi, the latest stable and official version (5.0.3) is already the one integrated into the container.
> 
> If you talk about the latest BETA, you may install it using the documented instruction: https://github.com/jlesage/docker-filebot#using-a-beta-version

Hi! A new (stable) version is available, version 5.1.1 released in September. Could you update please to this latest version. Or any way I can do this? Thanks

**Comment by jlesage** [comment]
Thanks for reporting, I will update the image with the latest version.
